#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 13
#define STATE_COUNT 105
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 49
#define ALIAS_COUNT 0
#define TOKEN_COUNT 32
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 4
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define PRODUCTION_ID_COUNT 4

enum {
  anon_sym_DOLLAR = 1,
  sym_anchor_begin = 2,
  aux_sym__raw_character_token1 = 3,
  anon_sym_DOT = 4,
  sym_all_letters_char = 5,
  sym_control_char = 6,
  sym_digit_char = 7,
  sym_printable_char = 8,
  sym_lowercase_char = 9,
  sym_punctuation_char = 10,
  sym_space_char = 11,
  sym_uppercase_char = 12,
  sym_alphanumeric_char = 13,
  sym_hexadecimal_char = 14,
  sym_escape_char = 15,
  sym_capture_index = 16,
  anon_sym_b = 17,
  aux_sym_balanced_match_token1 = 18,
  anon_sym_PERCENTf = 19,
  sym_zero_or_more = 20,
  anon_sym_DASH = 21,
  sym_one_or_more = 22,
  sym_zero_or_one = 23,
  anon_sym_PERCENT = 24,
  aux_sym_range_token1 = 25,
  anon_sym_LBRACK = 26,
  anon_sym_RBRACK = 27,
  anon_sym_LBRACK_CARET = 28,
  anon_sym_DASH2 = 29,
  anon_sym_LPAREN = 30,
  anon_sym_RPAREN = 31,
  sym_pattern = 32,
  sym_anchor_end = 33,
  sym__raw_character = 34,
  sym_character = 35,
  sym_balanced_match = 36,
  sym_frontier_pattern = 37,
  sym_shortest_zero_or_more = 38,
  sym__class = 39,
  sym_class = 40,
  sym_range = 41,
  sym_set = 42,
  sym_negated_set = 43,
  sym_capture = 44,
  aux_sym_pattern_repeat1 = 45,
  aux_sym_set_repeat1 = 46,
  aux_sym_negated_set_repeat1 = 47,
  aux_sym_capture_repeat1 = 48,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_DOLLAR] = "$",
  [sym_anchor_begin] = "anchor_begin",
  [aux_sym__raw_character_token1] = "_raw_character_token1",
  [anon_sym_DOT] = ".",
  [sym_all_letters_char] = "all_letters_char",
  [sym_control_char] = "control_char",
  [sym_digit_char] = "digit_char",
  [sym_printable_char] = "printable_char",
  [sym_lowercase_char] = "lowercase_char",
  [sym_punctuation_char] = "punctuation_char",
  [sym_space_char] = "space_char",
  [sym_uppercase_char] = "uppercase_char",
  [sym_alphanumeric_char] = "alphanumeric_char",
  [sym_hexadecimal_char] = "hexadecimal_char",
  [sym_escape_char] = "escape_char",
  [sym_capture_index] = "capture_index",
  [anon_sym_b] = "b",
  [aux_sym_balanced_match_token1] = "character",
  [anon_sym_PERCENTf] = "%f",
  [sym_zero_or_more] = "zero_or_more",
  [anon_sym_DASH] = "-",
  [sym_one_or_more] = "one_or_more",
  [sym_zero_or_one] = "zero_or_one",
  [anon_sym_PERCENT] = "%",
  [aux_sym_range_token1] = "character",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LBRACK_CARET] = "[^",
  [anon_sym_DASH2] = "character",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [sym_pattern] = "pattern",
  [sym_anchor_end] = "anchor_end",
  [sym__raw_character] = "_raw_character",
  [sym_character] = "character",
  [sym_balanced_match] = "balanced_match",
  [sym_frontier_pattern] = "frontier_pattern",
  [sym_shortest_zero_or_more] = "shortest_zero_or_more",
  [sym__class] = "_class",
  [sym_class] = "class",
  [sym_range] = "range",
  [sym_set] = "set",
  [sym_negated_set] = "negated_set",
  [sym_capture] = "capture",
  [aux_sym_pattern_repeat1] = "pattern_repeat1",
  [aux_sym_set_repeat1] = "set_repeat1",
  [aux_sym_negated_set_repeat1] = "negated_set_repeat1",
  [aux_sym_capture_repeat1] = "capture_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_DOLLAR] = anon_sym_DOLLAR,
  [sym_anchor_begin] = sym_anchor_begin,
  [aux_sym__raw_character_token1] = aux_sym__raw_character_token1,
  [anon_sym_DOT] = anon_sym_DOT,
  [sym_all_letters_char] = sym_all_letters_char,
  [sym_control_char] = sym_control_char,
  [sym_digit_char] = sym_digit_char,
  [sym_printable_char] = sym_printable_char,
  [sym_lowercase_char] = sym_lowercase_char,
  [sym_punctuation_char] = sym_punctuation_char,
  [sym_space_char] = sym_space_char,
  [sym_uppercase_char] = sym_uppercase_char,
  [sym_alphanumeric_char] = sym_alphanumeric_char,
  [sym_hexadecimal_char] = sym_hexadecimal_char,
  [sym_escape_char] = sym_escape_char,
  [sym_capture_index] = sym_capture_index,
  [anon_sym_b] = anon_sym_b,
  [aux_sym_balanced_match_token1] = sym_character,
  [anon_sym_PERCENTf] = anon_sym_PERCENTf,
  [sym_zero_or_more] = sym_zero_or_more,
  [anon_sym_DASH] = anon_sym_DASH,
  [sym_one_or_more] = sym_one_or_more,
  [sym_zero_or_one] = sym_zero_or_one,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [aux_sym_range_token1] = sym_character,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LBRACK_CARET] = anon_sym_LBRACK_CARET,
  [anon_sym_DASH2] = sym_character,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_pattern] = sym_pattern,
  [sym_anchor_end] = sym_anchor_end,
  [sym__raw_character] = sym__raw_character,
  [sym_character] = sym_character,
  [sym_balanced_match] = sym_balanced_match,
  [sym_frontier_pattern] = sym_frontier_pattern,
  [sym_shortest_zero_or_more] = sym_shortest_zero_or_more,
  [sym__class] = sym__class,
  [sym_class] = sym_class,
  [sym_range] = sym_range,
  [sym_set] = sym_set,
  [sym_negated_set] = sym_negated_set,
  [sym_capture] = sym_capture,
  [aux_sym_pattern_repeat1] = aux_sym_pattern_repeat1,
  [aux_sym_set_repeat1] = aux_sym_set_repeat1,
  [aux_sym_negated_set_repeat1] = aux_sym_negated_set_repeat1,
  [aux_sym_capture_repeat1] = aux_sym_capture_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_DOLLAR] = {
    .visible = true,
    .named = false,
  },
  [sym_anchor_begin] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__raw_character_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [sym_all_letters_char] = {
    .visible = true,
    .named = true,
  },
  [sym_control_char] = {
    .visible = true,
    .named = true,
  },
  [sym_digit_char] = {
    .visible = true,
    .named = true,
  },
  [sym_printable_char] = {
    .visible = true,
    .named = true,
  },
  [sym_lowercase_char] = {
    .visible = true,
    .named = true,
  },
  [sym_punctuation_char] = {
    .visible = true,
    .named = true,
  },
  [sym_space_char] = {
    .visible = true,
    .named = true,
  },
  [sym_uppercase_char] = {
    .visible = true,
    .named = true,
  },
  [sym_alphanumeric_char] = {
    .visible = true,
    .named = true,
  },
  [sym_hexadecimal_char] = {
    .visible = true,
    .named = true,
  },
  [sym_escape_char] = {
    .visible = true,
    .named = true,
  },
  [sym_capture_index] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_b] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_balanced_match_token1] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_PERCENTf] = {
    .visible = true,
    .named = false,
  },
  [sym_zero_or_more] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [sym_one_or_more] = {
    .visible = true,
    .named = true,
  },
  [sym_zero_or_one] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_range_token1] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK_CARET] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH2] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_pattern] = {
    .visible = true,
    .named = true,
  },
  [sym_anchor_end] = {
    .visible = true,
    .named = true,
  },
  [sym__raw_character] = {
    .visible = false,
    .named = true,
  },
  [sym_character] = {
    .visible = true,
    .named = true,
  },
  [sym_balanced_match] = {
    .visible = true,
    .named = true,
  },
  [sym_frontier_pattern] = {
    .visible = true,
    .named = true,
  },
  [sym_shortest_zero_or_more] = {
    .visible = true,
    .named = true,
  },
  [sym__class] = {
    .visible = false,
    .named = true,
  },
  [sym_class] = {
    .visible = true,
    .named = true,
  },
  [sym_range] = {
    .visible = true,
    .named = true,
  },
  [sym_set] = {
    .visible = true,
    .named = true,
  },
  [sym_negated_set] = {
    .visible = true,
    .named = true,
  },
  [sym_capture] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_pattern_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_set_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_negated_set_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_capture_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_first = 1,
  field_from = 2,
  field_last = 3,
  field_to = 4,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_first] = "first",
  [field_from] = "from",
  [field_last] = "last",
  [field_to] = "to",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [2] = {.index = 0, .length = 2},
  [3] = {.index = 2, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_first, 1},
    {field_last, 2},
  [2] =
    {field_from, 0},
    {field_to, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [0] = sym_character,
  },
  [3] = {
    [0] = sym_character,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  sym__raw_character, 2,
    sym__raw_character,
    sym_character,
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 6,
  [8] = 8,
  [9] = 8,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 12,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 12,
  [19] = 11,
  [20] = 20,
  [21] = 12,
  [22] = 17,
  [23] = 23,
  [24] = 14,
  [25] = 11,
  [26] = 26,
  [27] = 17,
  [28] = 20,
  [29] = 11,
  [30] = 16,
  [31] = 31,
  [32] = 15,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 17,
  [37] = 35,
  [38] = 31,
  [39] = 23,
  [40] = 26,
  [41] = 34,
  [42] = 33,
  [43] = 43,
  [44] = 44,
  [45] = 26,
  [46] = 23,
  [47] = 47,
  [48] = 43,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 44,
  [57] = 57,
  [58] = 44,
  [59] = 44,
  [60] = 43,
  [61] = 43,
  [62] = 62,
  [63] = 62,
  [64] = 64,
  [65] = 47,
  [66] = 54,
  [67] = 64,
  [68] = 62,
  [69] = 26,
  [70] = 23,
  [71] = 62,
  [72] = 51,
  [73] = 53,
  [74] = 57,
  [75] = 64,
  [76] = 64,
  [77] = 31,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 31,
  [82] = 33,
  [83] = 34,
  [84] = 80,
  [85] = 85,
  [86] = 34,
  [87] = 33,
  [88] = 88,
  [89] = 89,
  [90] = 89,
  [91] = 91,
  [92] = 92,
  [93] = 91,
  [94] = 91,
  [95] = 91,
  [96] = 96,
  [97] = 96,
  [98] = 98,
  [99] = 98,
  [100] = 100,
  [101] = 98,
  [102] = 102,
  [103] = 103,
  [104] = 98,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(18);
      if (lookahead == '\n') SKIP(16)
      if (lookahead == '$') ADVANCE(19);
      if (lookahead == '%') ADVANCE(43);
      if (lookahead == '(') ADVANCE(50);
      if (lookahead == ')') ADVANCE(51);
      if (lookahead == '*') ADVANCE(38);
      if (lookahead == '+') ADVANCE(40);
      if (lookahead == '-') ADVANCE(39);
      if (lookahead == '.') ADVANCE(22);
      if (lookahead == '?') ADVANCE(41);
      if (lookahead == '[') ADVANCE(46);
      if (lookahead == ']') ADVANCE(47);
      if (lookahead == '^') ADVANCE(20);
      if (lookahead == 'a') ADVANCE(23);
      if (lookahead == 'b') ADVANCE(35);
      if (lookahead == 'c') ADVANCE(24);
      if (lookahead == 'd') ADVANCE(25);
      if (lookahead == 'g') ADVANCE(26);
      if (lookahead == 'l') ADVANCE(27);
      if (lookahead == 'p') ADVANCE(28);
      if (lookahead == 's') ADVANCE(29);
      if (lookahead == 'u') ADVANCE(30);
      if (lookahead == 'w') ADVANCE(31);
      if (lookahead == 'x') ADVANCE(32);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(21);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(21);
      if (lookahead != 0) ADVANCE(21);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(9)
      if (lookahead == '%') ADVANCE(43);
      if (lookahead == '(') ADVANCE(50);
      if (lookahead == ')') ADVANCE(51);
      if (lookahead == '*') ADVANCE(38);
      if (lookahead == '+') ADVANCE(40);
      if (lookahead == '-') ADVANCE(39);
      if (lookahead == '.') ADVANCE(22);
      if (lookahead == '?') ADVANCE(41);
      if (lookahead == '[') ADVANCE(46);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(21);
      if (lookahead != 0) ADVANCE(21);
      END_STATE();
    case 2:
      if (lookahead == '\n') SKIP(9)
      if (lookahead == '%') ADVANCE(43);
      if (lookahead == '(') ADVANCE(50);
      if (lookahead == ')') ADVANCE(51);
      if (lookahead == '.') ADVANCE(22);
      if (lookahead == '[') ADVANCE(46);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(21);
      if (lookahead != 0) ADVANCE(21);
      END_STATE();
    case 3:
      if (lookahead == '\n') SKIP(9)
      if (lookahead == '%') ADVANCE(42);
      if (lookahead == '-') ADVANCE(39);
      if (lookahead == '.') ADVANCE(22);
      if (lookahead == ']') ADVANCE(47);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(21);
      if (lookahead != 0 &&
          lookahead != '(' &&
          lookahead != '[') ADVANCE(21);
      END_STATE();
    case 4:
      if (lookahead == '\n') SKIP(9)
      if (lookahead == '%') ADVANCE(42);
      if (lookahead == '-') ADVANCE(39);
      if (lookahead == '.') ADVANCE(22);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(21);
      if (lookahead != 0 &&
          lookahead != '(' &&
          lookahead != '[') ADVANCE(21);
      END_STATE();
    case 5:
      if (lookahead == '\n') SKIP(8)
      if (lookahead == '%') ADVANCE(42);
      if (lookahead == '-') ADVANCE(39);
      if (lookahead == '.') ADVANCE(22);
      if (lookahead == ']') ADVANCE(47);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(21);
      if (lookahead != 0 &&
          lookahead != '(' &&
          lookahead != '[') ADVANCE(21);
      END_STATE();
    case 6:
      if (lookahead == '\n') SKIP(8)
      if (lookahead == '%') ADVANCE(42);
      if (lookahead == '-') ADVANCE(49);
      if (lookahead == '.') ADVANCE(22);
      if (lookahead == ']') ADVANCE(47);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(21);
      if (lookahead != 0 &&
          lookahead != '(' &&
          lookahead != '[') ADVANCE(21);
      END_STATE();
    case 7:
      if (lookahead == '\n') SKIP(8)
      if (lookahead == '%') ADVANCE(42);
      if (lookahead == '-') ADVANCE(49);
      if (lookahead == '.') ADVANCE(22);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(21);
      if (lookahead != 0 &&
          lookahead != '(' &&
          lookahead != '[') ADVANCE(21);
      END_STATE();
    case 8:
      if (lookahead == '-') ADVANCE(49);
      if (lookahead == '.') ADVANCE(22);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(8)
      END_STATE();
    case 9:
      if (lookahead == '.') ADVANCE(22);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(9)
      END_STATE();
    case 10:
      if (lookahead == 'a') ADVANCE(23);
      if (lookahead == 'b') ADVANCE(35);
      if (lookahead == 'c') ADVANCE(24);
      if (lookahead == 'd') ADVANCE(25);
      if (lookahead == 'g') ADVANCE(26);
      if (lookahead == 'l') ADVANCE(27);
      if (lookahead == 'p') ADVANCE(28);
      if (lookahead == 's') ADVANCE(29);
      if (lookahead == 'u') ADVANCE(30);
      if (lookahead == 'w') ADVANCE(31);
      if (lookahead == 'x') ADVANCE(32);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(34);
      if (lookahead != 0 &&
          lookahead != '0' &&
          (lookahead < 'A' || 'Z' < lookahead) &&
          lookahead != '_' &&
          (lookahead < 'e' || 'z' < lookahead)) ADVANCE(33);
      END_STATE();
    case 11:
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(45);
      if (lookahead != 0 &&
          lookahead != ']') ADVANCE(44);
      END_STATE();
    case 12:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(36);
      END_STATE();
    case 13:
      if (eof) ADVANCE(18);
      if (lookahead == '\n') SKIP(17)
      if (lookahead == '$') ADVANCE(19);
      if (lookahead == '%') ADVANCE(43);
      if (lookahead == '(') ADVANCE(50);
      if (lookahead == '*') ADVANCE(38);
      if (lookahead == '+') ADVANCE(40);
      if (lookahead == '-') ADVANCE(39);
      if (lookahead == '.') ADVANCE(22);
      if (lookahead == '?') ADVANCE(41);
      if (lookahead == '[') ADVANCE(46);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(21);
      if (lookahead != 0) ADVANCE(21);
      END_STATE();
    case 14:
      if (eof) ADVANCE(18);
      if (lookahead == '\n') SKIP(17)
      if (lookahead == '$') ADVANCE(19);
      if (lookahead == '%') ADVANCE(43);
      if (lookahead == '(') ADVANCE(50);
      if (lookahead == '.') ADVANCE(22);
      if (lookahead == '[') ADVANCE(46);
      if (lookahead == '^') ADVANCE(20);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(21);
      if (lookahead != 0) ADVANCE(21);
      END_STATE();
    case 15:
      if (eof) ADVANCE(18);
      if (lookahead == '\n') SKIP(17)
      if (lookahead == '$') ADVANCE(19);
      if (lookahead == '%') ADVANCE(43);
      if (lookahead == '(') ADVANCE(50);
      if (lookahead == '.') ADVANCE(22);
      if (lookahead == '[') ADVANCE(46);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(21);
      if (lookahead != 0) ADVANCE(21);
      END_STATE();
    case 16:
      if (eof) ADVANCE(18);
      if (lookahead == '-') ADVANCE(49);
      if (lookahead == '.') ADVANCE(22);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(16)
      END_STATE();
    case 17:
      if (eof) ADVANCE(18);
      if (lookahead == '.') ADVANCE(22);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(17)
      END_STATE();
    case 18:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_DOLLAR);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_anchor_begin);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(aux_sym__raw_character_token1);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_all_letters_char);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_control_char);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_digit_char);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_printable_char);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_lowercase_char);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_punctuation_char);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_space_char);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_uppercase_char);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_alphanumeric_char);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_hexadecimal_char);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_escape_char);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_capture_index);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_b);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(aux_sym_balanced_match_token1);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_PERCENTf);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_zero_or_more);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_one_or_more);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_zero_or_one);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      if (lookahead == 'f') ADVANCE(37);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(aux_sym_range_token1);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(aux_sym_range_token1);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(45);
      if (lookahead != 0 &&
          lookahead != ']') ADVANCE(44);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      if (lookahead == '^') ADVANCE(48);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_LBRACK_CARET);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_DASH2);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 14},
  [2] = {.lex_state = 15},
  [3] = {.lex_state = 15},
  [4] = {.lex_state = 15},
  [5] = {.lex_state = 15},
  [6] = {.lex_state = 2},
  [7] = {.lex_state = 2},
  [8] = {.lex_state = 2},
  [9] = {.lex_state = 2},
  [10] = {.lex_state = 2},
  [11] = {.lex_state = 13},
  [12] = {.lex_state = 10},
  [13] = {.lex_state = 10},
  [14] = {.lex_state = 13},
  [15] = {.lex_state = 13},
  [16] = {.lex_state = 13},
  [17] = {.lex_state = 13},
  [18] = {.lex_state = 10},
  [19] = {.lex_state = 13},
  [20] = {.lex_state = 13},
  [21] = {.lex_state = 10},
  [22] = {.lex_state = 13},
  [23] = {.lex_state = 13},
  [24] = {.lex_state = 1},
  [25] = {.lex_state = 1},
  [26] = {.lex_state = 13},
  [27] = {.lex_state = 1},
  [28] = {.lex_state = 1},
  [29] = {.lex_state = 1},
  [30] = {.lex_state = 1},
  [31] = {.lex_state = 13},
  [32] = {.lex_state = 1},
  [33] = {.lex_state = 13},
  [34] = {.lex_state = 13},
  [35] = {.lex_state = 13},
  [36] = {.lex_state = 1},
  [37] = {.lex_state = 1},
  [38] = {.lex_state = 1},
  [39] = {.lex_state = 1},
  [40] = {.lex_state = 1},
  [41] = {.lex_state = 1},
  [42] = {.lex_state = 1},
  [43] = {.lex_state = 3},
  [44] = {.lex_state = 6},
  [45] = {.lex_state = 15},
  [46] = {.lex_state = 15},
  [47] = {.lex_state = 15},
  [48] = {.lex_state = 3},
  [49] = {.lex_state = 15},
  [50] = {.lex_state = 3},
  [51] = {.lex_state = 15},
  [52] = {.lex_state = 6},
  [53] = {.lex_state = 15},
  [54] = {.lex_state = 15},
  [55] = {.lex_state = 15},
  [56] = {.lex_state = 6},
  [57] = {.lex_state = 15},
  [58] = {.lex_state = 6},
  [59] = {.lex_state = 6},
  [60] = {.lex_state = 3},
  [61] = {.lex_state = 3},
  [62] = {.lex_state = 7},
  [63] = {.lex_state = 7},
  [64] = {.lex_state = 4},
  [65] = {.lex_state = 2},
  [66] = {.lex_state = 2},
  [67] = {.lex_state = 4},
  [68] = {.lex_state = 7},
  [69] = {.lex_state = 2},
  [70] = {.lex_state = 2},
  [71] = {.lex_state = 7},
  [72] = {.lex_state = 2},
  [73] = {.lex_state = 2},
  [74] = {.lex_state = 2},
  [75] = {.lex_state = 4},
  [76] = {.lex_state = 4},
  [77] = {.lex_state = 5},
  [78] = {.lex_state = 5},
  [79] = {.lex_state = 3},
  [80] = {.lex_state = 3},
  [81] = {.lex_state = 3},
  [82] = {.lex_state = 3},
  [83] = {.lex_state = 3},
  [84] = {.lex_state = 6},
  [85] = {.lex_state = 6},
  [86] = {.lex_state = 6},
  [87] = {.lex_state = 6},
  [88] = {.lex_state = 3},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 12},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 12},
  [94] = {.lex_state = 12},
  [95] = {.lex_state = 12},
  [96] = {.lex_state = 11},
  [97] = {.lex_state = 11},
  [98] = {.lex_state = 12},
  [99] = {.lex_state = 12},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 12},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 12},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_DOLLAR] = ACTIONS(1),
    [sym_anchor_begin] = ACTIONS(1),
    [aux_sym__raw_character_token1] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [sym_all_letters_char] = ACTIONS(1),
    [sym_control_char] = ACTIONS(1),
    [sym_digit_char] = ACTIONS(1),
    [sym_printable_char] = ACTIONS(1),
    [sym_lowercase_char] = ACTIONS(1),
    [sym_punctuation_char] = ACTIONS(1),
    [sym_space_char] = ACTIONS(1),
    [sym_uppercase_char] = ACTIONS(1),
    [sym_alphanumeric_char] = ACTIONS(1),
    [sym_hexadecimal_char] = ACTIONS(1),
    [sym_capture_index] = ACTIONS(1),
    [anon_sym_b] = ACTIONS(1),
    [anon_sym_PERCENTf] = ACTIONS(1),
    [sym_zero_or_more] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [sym_one_or_more] = ACTIONS(1),
    [sym_zero_or_one] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LBRACK_CARET] = ACTIONS(1),
    [anon_sym_DASH2] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
  },
  [1] = {
    [sym_pattern] = STATE(103),
    [sym_anchor_end] = STATE(92),
    [sym__raw_character] = STATE(15),
    [sym_character] = STATE(2),
    [sym_frontier_pattern] = STATE(16),
    [sym__class] = STATE(16),
    [sym_class] = STATE(2),
    [sym_set] = STATE(2),
    [sym_negated_set] = STATE(2),
    [sym_capture] = STATE(2),
    [aux_sym_pattern_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_DOLLAR] = ACTIONS(5),
    [sym_anchor_begin] = ACTIONS(7),
    [aux_sym__raw_character_token1] = ACTIONS(9),
    [anon_sym_DOT] = ACTIONS(9),
    [anon_sym_PERCENTf] = ACTIONS(11),
    [anon_sym_PERCENT] = ACTIONS(13),
    [anon_sym_LBRACK] = ACTIONS(15),
    [anon_sym_LBRACK_CARET] = ACTIONS(17),
    [anon_sym_LPAREN] = ACTIONS(19),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 12,
    ACTIONS(5), 1,
      anon_sym_DOLLAR,
    ACTIONS(11), 1,
      anon_sym_PERCENTf,
    ACTIONS(13), 1,
      anon_sym_PERCENT,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      anon_sym_LBRACK_CARET,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(21), 1,
      ts_builtin_sym_end,
    STATE(15), 1,
      sym__raw_character,
    STATE(102), 1,
      sym_anchor_end,
    ACTIONS(9), 2,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
    STATE(16), 2,
      sym_frontier_pattern,
      sym__class,
    STATE(5), 6,
      sym_character,
      sym_class,
      sym_set,
      sym_negated_set,
      sym_capture,
      aux_sym_pattern_repeat1,
  [44] = 12,
    ACTIONS(5), 1,
      anon_sym_DOLLAR,
    ACTIONS(11), 1,
      anon_sym_PERCENTf,
    ACTIONS(13), 1,
      anon_sym_PERCENT,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      anon_sym_LBRACK_CARET,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(21), 1,
      ts_builtin_sym_end,
    STATE(15), 1,
      sym__raw_character,
    STATE(102), 1,
      sym_anchor_end,
    ACTIONS(9), 2,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
    STATE(16), 2,
      sym_frontier_pattern,
      sym__class,
    STATE(4), 6,
      sym_character,
      sym_class,
      sym_set,
      sym_negated_set,
      sym_capture,
      aux_sym_pattern_repeat1,
  [88] = 12,
    ACTIONS(5), 1,
      anon_sym_DOLLAR,
    ACTIONS(11), 1,
      anon_sym_PERCENTf,
    ACTIONS(13), 1,
      anon_sym_PERCENT,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      anon_sym_LBRACK_CARET,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      ts_builtin_sym_end,
    STATE(15), 1,
      sym__raw_character,
    STATE(100), 1,
      sym_anchor_end,
    ACTIONS(9), 2,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
    STATE(16), 2,
      sym_frontier_pattern,
      sym__class,
    STATE(5), 6,
      sym_character,
      sym_class,
      sym_set,
      sym_negated_set,
      sym_capture,
      aux_sym_pattern_repeat1,
  [132] = 11,
    ACTIONS(25), 1,
      ts_builtin_sym_end,
    ACTIONS(27), 1,
      anon_sym_DOLLAR,
    ACTIONS(33), 1,
      anon_sym_PERCENTf,
    ACTIONS(36), 1,
      anon_sym_PERCENT,
    ACTIONS(39), 1,
      anon_sym_LBRACK,
    ACTIONS(42), 1,
      anon_sym_LBRACK_CARET,
    ACTIONS(45), 1,
      anon_sym_LPAREN,
    STATE(15), 1,
      sym__raw_character,
    ACTIONS(30), 2,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
    STATE(16), 2,
      sym_frontier_pattern,
      sym__class,
    STATE(5), 6,
      sym_character,
      sym_class,
      sym_set,
      sym_negated_set,
      sym_capture,
      aux_sym_pattern_repeat1,
  [173] = 10,
    ACTIONS(50), 1,
      anon_sym_PERCENTf,
    ACTIONS(52), 1,
      anon_sym_PERCENT,
    ACTIONS(54), 1,
      anon_sym_LBRACK,
    ACTIONS(56), 1,
      anon_sym_LBRACK_CARET,
    ACTIONS(58), 1,
      anon_sym_LPAREN,
    ACTIONS(60), 1,
      anon_sym_RPAREN,
    STATE(32), 1,
      sym__raw_character,
    ACTIONS(48), 2,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
    STATE(30), 2,
      sym_frontier_pattern,
      sym__class,
    STATE(10), 6,
      sym_character,
      sym_class,
      sym_set,
      sym_negated_set,
      sym_capture,
      aux_sym_capture_repeat1,
  [211] = 10,
    ACTIONS(50), 1,
      anon_sym_PERCENTf,
    ACTIONS(52), 1,
      anon_sym_PERCENT,
    ACTIONS(54), 1,
      anon_sym_LBRACK,
    ACTIONS(56), 1,
      anon_sym_LBRACK_CARET,
    ACTIONS(58), 1,
      anon_sym_LPAREN,
    ACTIONS(62), 1,
      anon_sym_RPAREN,
    STATE(32), 1,
      sym__raw_character,
    ACTIONS(48), 2,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
    STATE(30), 2,
      sym_frontier_pattern,
      sym__class,
    STATE(10), 6,
      sym_character,
      sym_class,
      sym_set,
      sym_negated_set,
      sym_capture,
      aux_sym_capture_repeat1,
  [249] = 10,
    ACTIONS(50), 1,
      anon_sym_PERCENTf,
    ACTIONS(52), 1,
      anon_sym_PERCENT,
    ACTIONS(54), 1,
      anon_sym_LBRACK,
    ACTIONS(56), 1,
      anon_sym_LBRACK_CARET,
    ACTIONS(58), 1,
      anon_sym_LPAREN,
    ACTIONS(64), 1,
      anon_sym_RPAREN,
    STATE(32), 1,
      sym__raw_character,
    ACTIONS(48), 2,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
    STATE(30), 2,
      sym_frontier_pattern,
      sym__class,
    STATE(7), 6,
      sym_character,
      sym_class,
      sym_set,
      sym_negated_set,
      sym_capture,
      aux_sym_capture_repeat1,
  [287] = 10,
    ACTIONS(50), 1,
      anon_sym_PERCENTf,
    ACTIONS(52), 1,
      anon_sym_PERCENT,
    ACTIONS(54), 1,
      anon_sym_LBRACK,
    ACTIONS(56), 1,
      anon_sym_LBRACK_CARET,
    ACTIONS(58), 1,
      anon_sym_LPAREN,
    ACTIONS(66), 1,
      anon_sym_RPAREN,
    STATE(32), 1,
      sym__raw_character,
    ACTIONS(48), 2,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
    STATE(30), 2,
      sym_frontier_pattern,
      sym__class,
    STATE(6), 6,
      sym_character,
      sym_class,
      sym_set,
      sym_negated_set,
      sym_capture,
      aux_sym_capture_repeat1,
  [325] = 10,
    ACTIONS(71), 1,
      anon_sym_PERCENTf,
    ACTIONS(74), 1,
      anon_sym_PERCENT,
    ACTIONS(77), 1,
      anon_sym_LBRACK,
    ACTIONS(80), 1,
      anon_sym_LBRACK_CARET,
    ACTIONS(83), 1,
      anon_sym_LPAREN,
    ACTIONS(86), 1,
      anon_sym_RPAREN,
    STATE(32), 1,
      sym__raw_character,
    ACTIONS(68), 2,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
    STATE(30), 2,
      sym_frontier_pattern,
      sym__class,
    STATE(10), 6,
      sym_character,
      sym_class,
      sym_set,
      sym_negated_set,
      sym_capture,
      aux_sym_capture_repeat1,
  [363] = 3,
    STATE(23), 1,
      sym_shortest_zero_or_more,
    ACTIONS(90), 4,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
      anon_sym_LBRACK,
    ACTIONS(88), 9,
      ts_builtin_sym_end,
      anon_sym_DOLLAR,
      anon_sym_PERCENTf,
      sym_zero_or_more,
      anon_sym_DASH,
      sym_one_or_more,
      sym_zero_or_one,
      anon_sym_LBRACK_CARET,
      anon_sym_LPAREN,
  [384] = 3,
    ACTIONS(94), 1,
      anon_sym_b,
    STATE(33), 1,
      sym_balanced_match,
    ACTIONS(92), 12,
      sym_all_letters_char,
      sym_control_char,
      sym_digit_char,
      sym_printable_char,
      sym_lowercase_char,
      sym_punctuation_char,
      sym_space_char,
      sym_uppercase_char,
      sym_alphanumeric_char,
      sym_hexadecimal_char,
      sym_escape_char,
      sym_capture_index,
  [405] = 3,
    ACTIONS(98), 1,
      anon_sym_b,
    STATE(82), 1,
      sym_balanced_match,
    ACTIONS(96), 12,
      sym_all_letters_char,
      sym_control_char,
      sym_digit_char,
      sym_printable_char,
      sym_lowercase_char,
      sym_punctuation_char,
      sym_space_char,
      sym_uppercase_char,
      sym_alphanumeric_char,
      sym_hexadecimal_char,
      sym_escape_char,
      sym_capture_index,
  [426] = 5,
    ACTIONS(106), 1,
      anon_sym_DASH,
    STATE(47), 1,
      sym_shortest_zero_or_more,
    ACTIONS(104), 3,
      sym_zero_or_more,
      sym_one_or_more,
      sym_zero_or_one,
    ACTIONS(102), 4,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
      anon_sym_LBRACK,
    ACTIONS(100), 5,
      ts_builtin_sym_end,
      anon_sym_DOLLAR,
      anon_sym_PERCENTf,
      anon_sym_LBRACK_CARET,
      anon_sym_LPAREN,
  [451] = 5,
    ACTIONS(106), 1,
      anon_sym_DASH,
    STATE(57), 1,
      sym_shortest_zero_or_more,
    ACTIONS(112), 3,
      sym_zero_or_more,
      sym_one_or_more,
      sym_zero_or_one,
    ACTIONS(110), 4,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
      anon_sym_LBRACK,
    ACTIONS(108), 5,
      ts_builtin_sym_end,
      anon_sym_DOLLAR,
      anon_sym_PERCENTf,
      anon_sym_LBRACK_CARET,
      anon_sym_LPAREN,
  [476] = 5,
    ACTIONS(106), 1,
      anon_sym_DASH,
    STATE(51), 1,
      sym_shortest_zero_or_more,
    ACTIONS(118), 3,
      sym_zero_or_more,
      sym_one_or_more,
      sym_zero_or_one,
    ACTIONS(116), 4,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
      anon_sym_LBRACK,
    ACTIONS(114), 5,
      ts_builtin_sym_end,
      anon_sym_DOLLAR,
      anon_sym_PERCENTf,
      anon_sym_LBRACK_CARET,
      anon_sym_LPAREN,
  [501] = 5,
    ACTIONS(106), 1,
      anon_sym_DASH,
    STATE(45), 1,
      sym_shortest_zero_or_more,
    ACTIONS(124), 3,
      sym_zero_or_more,
      sym_one_or_more,
      sym_zero_or_one,
    ACTIONS(122), 4,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
      anon_sym_LBRACK,
    ACTIONS(120), 5,
      ts_builtin_sym_end,
      anon_sym_DOLLAR,
      anon_sym_PERCENTf,
      anon_sym_LBRACK_CARET,
      anon_sym_LPAREN,
  [526] = 3,
    ACTIONS(128), 1,
      anon_sym_b,
    STATE(42), 1,
      sym_balanced_match,
    ACTIONS(126), 12,
      sym_all_letters_char,
      sym_control_char,
      sym_digit_char,
      sym_printable_char,
      sym_lowercase_char,
      sym_punctuation_char,
      sym_space_char,
      sym_uppercase_char,
      sym_alphanumeric_char,
      sym_hexadecimal_char,
      sym_escape_char,
      sym_capture_index,
  [547] = 5,
    ACTIONS(106), 1,
      anon_sym_DASH,
    STATE(46), 1,
      sym_shortest_zero_or_more,
    ACTIONS(130), 3,
      sym_zero_or_more,
      sym_one_or_more,
      sym_zero_or_one,
    ACTIONS(90), 4,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
      anon_sym_LBRACK,
    ACTIONS(88), 5,
      ts_builtin_sym_end,
      anon_sym_DOLLAR,
      anon_sym_PERCENTf,
      anon_sym_LBRACK_CARET,
      anon_sym_LPAREN,
  [572] = 5,
    ACTIONS(106), 1,
      anon_sym_DASH,
    STATE(54), 1,
      sym_shortest_zero_or_more,
    ACTIONS(136), 3,
      sym_zero_or_more,
      sym_one_or_more,
      sym_zero_or_one,
    ACTIONS(134), 4,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
      anon_sym_LBRACK,
    ACTIONS(132), 5,
      ts_builtin_sym_end,
      anon_sym_DOLLAR,
      anon_sym_PERCENTf,
      anon_sym_LBRACK_CARET,
      anon_sym_LPAREN,
  [597] = 3,
    ACTIONS(140), 1,
      anon_sym_b,
    STATE(87), 1,
      sym_balanced_match,
    ACTIONS(138), 12,
      sym_all_letters_char,
      sym_control_char,
      sym_digit_char,
      sym_printable_char,
      sym_lowercase_char,
      sym_punctuation_char,
      sym_space_char,
      sym_uppercase_char,
      sym_alphanumeric_char,
      sym_hexadecimal_char,
      sym_escape_char,
      sym_capture_index,
  [618] = 3,
    STATE(26), 1,
      sym_shortest_zero_or_more,
    ACTIONS(122), 4,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
      anon_sym_LBRACK,
    ACTIONS(120), 9,
      ts_builtin_sym_end,
      anon_sym_DOLLAR,
      anon_sym_PERCENTf,
      sym_zero_or_more,
      anon_sym_DASH,
      sym_one_or_more,
      sym_zero_or_one,
      anon_sym_LBRACK_CARET,
      anon_sym_LPAREN,
  [639] = 2,
    ACTIONS(144), 4,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
      anon_sym_LBRACK,
    ACTIONS(142), 9,
      ts_builtin_sym_end,
      anon_sym_DOLLAR,
      anon_sym_PERCENTf,
      sym_zero_or_more,
      anon_sym_DASH,
      sym_one_or_more,
      sym_zero_or_one,
      anon_sym_LBRACK_CARET,
      anon_sym_LPAREN,
  [657] = 5,
    ACTIONS(148), 1,
      anon_sym_DASH,
    STATE(65), 1,
      sym_shortest_zero_or_more,
    ACTIONS(146), 3,
      sym_zero_or_more,
      sym_one_or_more,
      sym_zero_or_one,
    ACTIONS(100), 4,
      anon_sym_PERCENTf,
      anon_sym_LBRACK_CARET,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
    ACTIONS(102), 4,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
      anon_sym_LBRACK,
  [681] = 3,
    STATE(39), 1,
      sym_shortest_zero_or_more,
    ACTIONS(90), 4,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
      anon_sym_LBRACK,
    ACTIONS(88), 8,
      anon_sym_PERCENTf,
      sym_zero_or_more,
      anon_sym_DASH,
      sym_one_or_more,
      sym_zero_or_one,
      anon_sym_LBRACK_CARET,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [701] = 2,
    ACTIONS(152), 4,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
      anon_sym_LBRACK,
    ACTIONS(150), 9,
      ts_builtin_sym_end,
      anon_sym_DOLLAR,
      anon_sym_PERCENTf,
      sym_zero_or_more,
      anon_sym_DASH,
      sym_one_or_more,
      sym_zero_or_one,
      anon_sym_LBRACK_CARET,
      anon_sym_LPAREN,
  [719] = 5,
    ACTIONS(148), 1,
      anon_sym_DASH,
    STATE(69), 1,
      sym_shortest_zero_or_more,
    ACTIONS(154), 3,
      sym_zero_or_more,
      sym_one_or_more,
      sym_zero_or_one,
    ACTIONS(120), 4,
      anon_sym_PERCENTf,
      anon_sym_LBRACK_CARET,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
    ACTIONS(122), 4,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
      anon_sym_LBRACK,
  [743] = 5,
    ACTIONS(148), 1,
      anon_sym_DASH,
    STATE(66), 1,
      sym_shortest_zero_or_more,
    ACTIONS(156), 3,
      sym_zero_or_more,
      sym_one_or_more,
      sym_zero_or_one,
    ACTIONS(132), 4,
      anon_sym_PERCENTf,
      anon_sym_LBRACK_CARET,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
    ACTIONS(134), 4,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
      anon_sym_LBRACK,
  [767] = 5,
    ACTIONS(148), 1,
      anon_sym_DASH,
    STATE(70), 1,
      sym_shortest_zero_or_more,
    ACTIONS(158), 3,
      sym_zero_or_more,
      sym_one_or_more,
      sym_zero_or_one,
    ACTIONS(88), 4,
      anon_sym_PERCENTf,
      anon_sym_LBRACK_CARET,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
    ACTIONS(90), 4,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
      anon_sym_LBRACK,
  [791] = 5,
    ACTIONS(148), 1,
      anon_sym_DASH,
    STATE(72), 1,
      sym_shortest_zero_or_more,
    ACTIONS(160), 3,
      sym_zero_or_more,
      sym_one_or_more,
      sym_zero_or_one,
    ACTIONS(114), 4,
      anon_sym_PERCENTf,
      anon_sym_LBRACK_CARET,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
    ACTIONS(116), 4,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
      anon_sym_LBRACK,
  [815] = 2,
    ACTIONS(164), 4,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
      anon_sym_LBRACK,
    ACTIONS(162), 9,
      ts_builtin_sym_end,
      anon_sym_DOLLAR,
      anon_sym_PERCENTf,
      sym_zero_or_more,
      anon_sym_DASH,
      sym_one_or_more,
      sym_zero_or_one,
      anon_sym_LBRACK_CARET,
      anon_sym_LPAREN,
  [833] = 5,
    ACTIONS(148), 1,
      anon_sym_DASH,
    STATE(74), 1,
      sym_shortest_zero_or_more,
    ACTIONS(166), 3,
      sym_zero_or_more,
      sym_one_or_more,
      sym_zero_or_one,
    ACTIONS(108), 4,
      anon_sym_PERCENTf,
      anon_sym_LBRACK_CARET,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
    ACTIONS(110), 4,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
      anon_sym_LBRACK,
  [857] = 2,
    ACTIONS(170), 4,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
      anon_sym_LBRACK,
    ACTIONS(168), 9,
      ts_builtin_sym_end,
      anon_sym_DOLLAR,
      anon_sym_PERCENTf,
      sym_zero_or_more,
      anon_sym_DASH,
      sym_one_or_more,
      sym_zero_or_one,
      anon_sym_LBRACK_CARET,
      anon_sym_LPAREN,
  [875] = 2,
    ACTIONS(174), 4,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
      anon_sym_LBRACK,
    ACTIONS(172), 9,
      ts_builtin_sym_end,
      anon_sym_DOLLAR,
      anon_sym_PERCENTf,
      sym_zero_or_more,
      anon_sym_DASH,
      sym_one_or_more,
      sym_zero_or_one,
      anon_sym_LBRACK_CARET,
      anon_sym_LPAREN,
  [893] = 2,
    ACTIONS(178), 4,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
      anon_sym_LBRACK,
    ACTIONS(176), 9,
      ts_builtin_sym_end,
      anon_sym_DOLLAR,
      anon_sym_PERCENTf,
      sym_zero_or_more,
      anon_sym_DASH,
      sym_one_or_more,
      sym_zero_or_one,
      anon_sym_LBRACK_CARET,
      anon_sym_LPAREN,
  [911] = 3,
    STATE(40), 1,
      sym_shortest_zero_or_more,
    ACTIONS(122), 4,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
      anon_sym_LBRACK,
    ACTIONS(120), 8,
      anon_sym_PERCENTf,
      sym_zero_or_more,
      anon_sym_DASH,
      sym_one_or_more,
      sym_zero_or_one,
      anon_sym_LBRACK_CARET,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [931] = 2,
    ACTIONS(178), 4,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
      anon_sym_LBRACK,
    ACTIONS(176), 8,
      anon_sym_PERCENTf,
      sym_zero_or_more,
      anon_sym_DASH,
      sym_one_or_more,
      sym_zero_or_one,
      anon_sym_LBRACK_CARET,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [948] = 2,
    ACTIONS(164), 4,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
      anon_sym_LBRACK,
    ACTIONS(162), 8,
      anon_sym_PERCENTf,
      sym_zero_or_more,
      anon_sym_DASH,
      sym_one_or_more,
      sym_zero_or_one,
      anon_sym_LBRACK_CARET,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [965] = 2,
    ACTIONS(144), 4,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
      anon_sym_LBRACK,
    ACTIONS(142), 8,
      anon_sym_PERCENTf,
      sym_zero_or_more,
      anon_sym_DASH,
      sym_one_or_more,
      sym_zero_or_one,
      anon_sym_LBRACK_CARET,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [982] = 2,
    ACTIONS(152), 4,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
      anon_sym_LBRACK,
    ACTIONS(150), 8,
      anon_sym_PERCENTf,
      sym_zero_or_more,
      anon_sym_DASH,
      sym_one_or_more,
      sym_zero_or_one,
      anon_sym_LBRACK_CARET,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [999] = 2,
    ACTIONS(174), 4,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
      anon_sym_LBRACK,
    ACTIONS(172), 8,
      anon_sym_PERCENTf,
      sym_zero_or_more,
      anon_sym_DASH,
      sym_one_or_more,
      sym_zero_or_one,
      anon_sym_LBRACK_CARET,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [1016] = 2,
    ACTIONS(170), 4,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
      anon_sym_LBRACK,
    ACTIONS(168), 8,
      anon_sym_PERCENTf,
      sym_zero_or_more,
      anon_sym_DASH,
      sym_one_or_more,
      sym_zero_or_one,
      anon_sym_LBRACK_CARET,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [1033] = 6,
    ACTIONS(182), 1,
      anon_sym_DASH,
    ACTIONS(184), 1,
      anon_sym_PERCENT,
    ACTIONS(186), 1,
      anon_sym_RBRACK,
    STATE(88), 1,
      sym__raw_character,
    ACTIONS(180), 2,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
    STATE(50), 3,
      sym__class,
      sym_range,
      aux_sym_set_repeat1,
  [1055] = 6,
    ACTIONS(190), 1,
      anon_sym_PERCENT,
    ACTIONS(192), 1,
      anon_sym_RBRACK,
    ACTIONS(194), 1,
      anon_sym_DASH2,
    STATE(78), 1,
      sym__raw_character,
    ACTIONS(188), 2,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
    STATE(52), 3,
      sym__class,
      sym_range,
      aux_sym_negated_set_repeat1,
  [1077] = 2,
    ACTIONS(152), 4,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
      anon_sym_LBRACK,
    ACTIONS(150), 5,
      ts_builtin_sym_end,
      anon_sym_DOLLAR,
      anon_sym_PERCENTf,
      anon_sym_LBRACK_CARET,
      anon_sym_LPAREN,
  [1091] = 2,
    ACTIONS(144), 4,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
      anon_sym_LBRACK,
    ACTIONS(142), 5,
      ts_builtin_sym_end,
      anon_sym_DOLLAR,
      anon_sym_PERCENTf,
      anon_sym_LBRACK_CARET,
      anon_sym_LPAREN,
  [1105] = 2,
    ACTIONS(198), 4,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
      anon_sym_LBRACK,
    ACTIONS(196), 5,
      ts_builtin_sym_end,
      anon_sym_DOLLAR,
      anon_sym_PERCENTf,
      anon_sym_LBRACK_CARET,
      anon_sym_LPAREN,
  [1119] = 6,
    ACTIONS(182), 1,
      anon_sym_DASH,
    ACTIONS(184), 1,
      anon_sym_PERCENT,
    ACTIONS(200), 1,
      anon_sym_RBRACK,
    STATE(88), 1,
      sym__raw_character,
    ACTIONS(180), 2,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
    STATE(50), 3,
      sym__class,
      sym_range,
      aux_sym_set_repeat1,
  [1141] = 3,
    ACTIONS(202), 1,
      ts_builtin_sym_end,
    ACTIONS(204), 4,
      anon_sym_DOLLAR,
      anon_sym_PERCENTf,
      anon_sym_LBRACK_CARET,
      anon_sym_LPAREN,
    ACTIONS(206), 4,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
      anon_sym_LBRACK,
  [1157] = 6,
    ACTIONS(211), 1,
      anon_sym_DASH,
    ACTIONS(214), 1,
      anon_sym_PERCENT,
    ACTIONS(217), 1,
      anon_sym_RBRACK,
    STATE(88), 1,
      sym__raw_character,
    ACTIONS(208), 2,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
    STATE(50), 3,
      sym__class,
      sym_range,
      aux_sym_set_repeat1,
  [1179] = 2,
    ACTIONS(221), 4,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
      anon_sym_LBRACK,
    ACTIONS(219), 5,
      ts_builtin_sym_end,
      anon_sym_DOLLAR,
      anon_sym_PERCENTf,
      anon_sym_LBRACK_CARET,
      anon_sym_LPAREN,
  [1193] = 6,
    ACTIONS(226), 1,
      anon_sym_PERCENT,
    ACTIONS(229), 1,
      anon_sym_RBRACK,
    ACTIONS(231), 1,
      anon_sym_DASH2,
    STATE(78), 1,
      sym__raw_character,
    ACTIONS(223), 2,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
    STATE(52), 3,
      sym__class,
      sym_range,
      aux_sym_negated_set_repeat1,
  [1215] = 2,
    ACTIONS(236), 4,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
      anon_sym_LBRACK,
    ACTIONS(234), 5,
      ts_builtin_sym_end,
      anon_sym_DOLLAR,
      anon_sym_PERCENTf,
      anon_sym_LBRACK_CARET,
      anon_sym_LPAREN,
  [1229] = 2,
    ACTIONS(102), 4,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
      anon_sym_LBRACK,
    ACTIONS(100), 5,
      ts_builtin_sym_end,
      anon_sym_DOLLAR,
      anon_sym_PERCENTf,
      anon_sym_LBRACK_CARET,
      anon_sym_LPAREN,
  [1243] = 2,
    ACTIONS(206), 4,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
      anon_sym_LBRACK,
    ACTIONS(204), 5,
      ts_builtin_sym_end,
      anon_sym_DOLLAR,
      anon_sym_PERCENTf,
      anon_sym_LBRACK_CARET,
      anon_sym_LPAREN,
  [1257] = 6,
    ACTIONS(190), 1,
      anon_sym_PERCENT,
    ACTIONS(194), 1,
      anon_sym_DASH2,
    ACTIONS(238), 1,
      anon_sym_RBRACK,
    STATE(78), 1,
      sym__raw_character,
    ACTIONS(188), 2,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
    STATE(52), 3,
      sym__class,
      sym_range,
      aux_sym_negated_set_repeat1,
  [1279] = 2,
    ACTIONS(242), 4,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
      anon_sym_LBRACK,
    ACTIONS(240), 5,
      ts_builtin_sym_end,
      anon_sym_DOLLAR,
      anon_sym_PERCENTf,
      anon_sym_LBRACK_CARET,
      anon_sym_LPAREN,
  [1293] = 6,
    ACTIONS(190), 1,
      anon_sym_PERCENT,
    ACTIONS(194), 1,
      anon_sym_DASH2,
    ACTIONS(244), 1,
      anon_sym_RBRACK,
    STATE(78), 1,
      sym__raw_character,
    ACTIONS(188), 2,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
    STATE(52), 3,
      sym__class,
      sym_range,
      aux_sym_negated_set_repeat1,
  [1315] = 6,
    ACTIONS(190), 1,
      anon_sym_PERCENT,
    ACTIONS(194), 1,
      anon_sym_DASH2,
    ACTIONS(246), 1,
      anon_sym_RBRACK,
    STATE(78), 1,
      sym__raw_character,
    ACTIONS(188), 2,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
    STATE(52), 3,
      sym__class,
      sym_range,
      aux_sym_negated_set_repeat1,
  [1337] = 6,
    ACTIONS(182), 1,
      anon_sym_DASH,
    ACTIONS(184), 1,
      anon_sym_PERCENT,
    ACTIONS(248), 1,
      anon_sym_RBRACK,
    STATE(88), 1,
      sym__raw_character,
    ACTIONS(180), 2,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
    STATE(50), 3,
      sym__class,
      sym_range,
      aux_sym_set_repeat1,
  [1359] = 6,
    ACTIONS(182), 1,
      anon_sym_DASH,
    ACTIONS(184), 1,
      anon_sym_PERCENT,
    ACTIONS(250), 1,
      anon_sym_RBRACK,
    STATE(88), 1,
      sym__raw_character,
    ACTIONS(180), 2,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
    STATE(50), 3,
      sym__class,
      sym_range,
      aux_sym_set_repeat1,
  [1381] = 5,
    ACTIONS(190), 1,
      anon_sym_PERCENT,
    ACTIONS(194), 1,
      anon_sym_DASH2,
    STATE(78), 1,
      sym__raw_character,
    ACTIONS(188), 2,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
    STATE(56), 3,
      sym__class,
      sym_range,
      aux_sym_negated_set_repeat1,
  [1400] = 5,
    ACTIONS(190), 1,
      anon_sym_PERCENT,
    ACTIONS(194), 1,
      anon_sym_DASH2,
    STATE(78), 1,
      sym__raw_character,
    ACTIONS(188), 2,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
    STATE(59), 3,
      sym__class,
      sym_range,
      aux_sym_negated_set_repeat1,
  [1419] = 5,
    ACTIONS(182), 1,
      anon_sym_DASH,
    ACTIONS(184), 1,
      anon_sym_PERCENT,
    STATE(88), 1,
      sym__raw_character,
    ACTIONS(180), 2,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
    STATE(48), 3,
      sym__class,
      sym_range,
      aux_sym_set_repeat1,
  [1438] = 2,
    ACTIONS(196), 4,
      anon_sym_PERCENTf,
      anon_sym_LBRACK_CARET,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
    ACTIONS(198), 4,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
      anon_sym_LBRACK,
  [1451] = 2,
    ACTIONS(100), 4,
      anon_sym_PERCENTf,
      anon_sym_LBRACK_CARET,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
    ACTIONS(102), 4,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
      anon_sym_LBRACK,
  [1464] = 5,
    ACTIONS(182), 1,
      anon_sym_DASH,
    ACTIONS(184), 1,
      anon_sym_PERCENT,
    STATE(88), 1,
      sym__raw_character,
    ACTIONS(180), 2,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
    STATE(60), 3,
      sym__class,
      sym_range,
      aux_sym_set_repeat1,
  [1483] = 5,
    ACTIONS(190), 1,
      anon_sym_PERCENT,
    ACTIONS(194), 1,
      anon_sym_DASH2,
    STATE(78), 1,
      sym__raw_character,
    ACTIONS(188), 2,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
    STATE(58), 3,
      sym__class,
      sym_range,
      aux_sym_negated_set_repeat1,
  [1502] = 2,
    ACTIONS(150), 4,
      anon_sym_PERCENTf,
      anon_sym_LBRACK_CARET,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
    ACTIONS(152), 4,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
      anon_sym_LBRACK,
  [1515] = 2,
    ACTIONS(142), 4,
      anon_sym_PERCENTf,
      anon_sym_LBRACK_CARET,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
    ACTIONS(144), 4,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
      anon_sym_LBRACK,
  [1528] = 5,
    ACTIONS(190), 1,
      anon_sym_PERCENT,
    ACTIONS(194), 1,
      anon_sym_DASH2,
    STATE(78), 1,
      sym__raw_character,
    ACTIONS(188), 2,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
    STATE(44), 3,
      sym__class,
      sym_range,
      aux_sym_negated_set_repeat1,
  [1547] = 2,
    ACTIONS(219), 4,
      anon_sym_PERCENTf,
      anon_sym_LBRACK_CARET,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
    ACTIONS(221), 4,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
      anon_sym_LBRACK,
  [1560] = 2,
    ACTIONS(234), 4,
      anon_sym_PERCENTf,
      anon_sym_LBRACK_CARET,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
    ACTIONS(236), 4,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
      anon_sym_LBRACK,
  [1573] = 2,
    ACTIONS(240), 4,
      anon_sym_PERCENTf,
      anon_sym_LBRACK_CARET,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
    ACTIONS(242), 4,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
      anon_sym_LBRACK,
  [1586] = 5,
    ACTIONS(182), 1,
      anon_sym_DASH,
    ACTIONS(184), 1,
      anon_sym_PERCENT,
    STATE(88), 1,
      sym__raw_character,
    ACTIONS(180), 2,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
    STATE(61), 3,
      sym__class,
      sym_range,
      aux_sym_set_repeat1,
  [1605] = 5,
    ACTIONS(182), 1,
      anon_sym_DASH,
    ACTIONS(184), 1,
      anon_sym_PERCENT,
    STATE(88), 1,
      sym__raw_character,
    ACTIONS(180), 2,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
    STATE(43), 3,
      sym__class,
      sym_range,
      aux_sym_set_repeat1,
  [1624] = 2,
    ACTIONS(162), 3,
      anon_sym_DASH,
      anon_sym_PERCENT,
      anon_sym_RBRACK,
    ACTIONS(164), 3,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
      anon_sym_DASH2,
  [1635] = 3,
    ACTIONS(254), 1,
      anon_sym_DASH,
    ACTIONS(256), 2,
      anon_sym_PERCENT,
      anon_sym_RBRACK,
    ACTIONS(252), 3,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
      anon_sym_DASH2,
  [1648] = 2,
    ACTIONS(258), 2,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
    ACTIONS(260), 3,
      anon_sym_DASH,
      anon_sym_PERCENT,
      anon_sym_RBRACK,
  [1658] = 2,
    ACTIONS(262), 2,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
    ACTIONS(264), 3,
      anon_sym_DASH,
      anon_sym_PERCENT,
      anon_sym_RBRACK,
  [1668] = 2,
    ACTIONS(164), 2,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
    ACTIONS(162), 3,
      anon_sym_DASH,
      anon_sym_PERCENT,
      anon_sym_RBRACK,
  [1678] = 2,
    ACTIONS(170), 2,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
    ACTIONS(168), 3,
      anon_sym_DASH,
      anon_sym_PERCENT,
      anon_sym_RBRACK,
  [1688] = 2,
    ACTIONS(174), 2,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
    ACTIONS(172), 3,
      anon_sym_DASH,
      anon_sym_PERCENT,
      anon_sym_RBRACK,
  [1698] = 2,
    ACTIONS(264), 2,
      anon_sym_PERCENT,
      anon_sym_RBRACK,
    ACTIONS(262), 3,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
      anon_sym_DASH2,
  [1708] = 2,
    ACTIONS(256), 2,
      anon_sym_PERCENT,
      anon_sym_RBRACK,
    ACTIONS(252), 3,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
      anon_sym_DASH2,
  [1718] = 2,
    ACTIONS(172), 2,
      anon_sym_PERCENT,
      anon_sym_RBRACK,
    ACTIONS(174), 3,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
      anon_sym_DASH2,
  [1728] = 2,
    ACTIONS(168), 2,
      anon_sym_PERCENT,
      anon_sym_RBRACK,
    ACTIONS(170), 3,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
      anon_sym_DASH2,
  [1738] = 3,
    ACTIONS(266), 1,
      anon_sym_DASH,
    ACTIONS(258), 2,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
    ACTIONS(260), 2,
      anon_sym_PERCENT,
      anon_sym_RBRACK,
  [1750] = 3,
    ACTIONS(269), 1,
      anon_sym_LBRACK,
    ACTIONS(271), 1,
      anon_sym_LBRACK_CARET,
    STATE(35), 2,
      sym_set,
      sym_negated_set,
  [1761] = 3,
    ACTIONS(273), 1,
      anon_sym_LBRACK,
    ACTIONS(275), 1,
      anon_sym_LBRACK_CARET,
    STATE(37), 2,
      sym_set,
      sym_negated_set,
  [1772] = 1,
    ACTIONS(277), 1,
      aux_sym_balanced_match_token1,
  [1776] = 1,
    ACTIONS(21), 1,
      ts_builtin_sym_end,
  [1780] = 1,
    ACTIONS(279), 1,
      aux_sym_balanced_match_token1,
  [1784] = 1,
    ACTIONS(281), 1,
      aux_sym_balanced_match_token1,
  [1788] = 1,
    ACTIONS(283), 1,
      aux_sym_balanced_match_token1,
  [1792] = 1,
    ACTIONS(285), 1,
      aux_sym_range_token1,
  [1796] = 1,
    ACTIONS(287), 1,
      aux_sym_range_token1,
  [1800] = 1,
    ACTIONS(289), 1,
      aux_sym_balanced_match_token1,
  [1804] = 1,
    ACTIONS(291), 1,
      aux_sym_balanced_match_token1,
  [1808] = 1,
    ACTIONS(293), 1,
      ts_builtin_sym_end,
  [1812] = 1,
    ACTIONS(295), 1,
      aux_sym_balanced_match_token1,
  [1816] = 1,
    ACTIONS(23), 1,
      ts_builtin_sym_end,
  [1820] = 1,
    ACTIONS(297), 1,
      ts_builtin_sym_end,
  [1824] = 1,
    ACTIONS(299), 1,
      aux_sym_balanced_match_token1,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 44,
  [SMALL_STATE(4)] = 88,
  [SMALL_STATE(5)] = 132,
  [SMALL_STATE(6)] = 173,
  [SMALL_STATE(7)] = 211,
  [SMALL_STATE(8)] = 249,
  [SMALL_STATE(9)] = 287,
  [SMALL_STATE(10)] = 325,
  [SMALL_STATE(11)] = 363,
  [SMALL_STATE(12)] = 384,
  [SMALL_STATE(13)] = 405,
  [SMALL_STATE(14)] = 426,
  [SMALL_STATE(15)] = 451,
  [SMALL_STATE(16)] = 476,
  [SMALL_STATE(17)] = 501,
  [SMALL_STATE(18)] = 526,
  [SMALL_STATE(19)] = 547,
  [SMALL_STATE(20)] = 572,
  [SMALL_STATE(21)] = 597,
  [SMALL_STATE(22)] = 618,
  [SMALL_STATE(23)] = 639,
  [SMALL_STATE(24)] = 657,
  [SMALL_STATE(25)] = 681,
  [SMALL_STATE(26)] = 701,
  [SMALL_STATE(27)] = 719,
  [SMALL_STATE(28)] = 743,
  [SMALL_STATE(29)] = 767,
  [SMALL_STATE(30)] = 791,
  [SMALL_STATE(31)] = 815,
  [SMALL_STATE(32)] = 833,
  [SMALL_STATE(33)] = 857,
  [SMALL_STATE(34)] = 875,
  [SMALL_STATE(35)] = 893,
  [SMALL_STATE(36)] = 911,
  [SMALL_STATE(37)] = 931,
  [SMALL_STATE(38)] = 948,
  [SMALL_STATE(39)] = 965,
  [SMALL_STATE(40)] = 982,
  [SMALL_STATE(41)] = 999,
  [SMALL_STATE(42)] = 1016,
  [SMALL_STATE(43)] = 1033,
  [SMALL_STATE(44)] = 1055,
  [SMALL_STATE(45)] = 1077,
  [SMALL_STATE(46)] = 1091,
  [SMALL_STATE(47)] = 1105,
  [SMALL_STATE(48)] = 1119,
  [SMALL_STATE(49)] = 1141,
  [SMALL_STATE(50)] = 1157,
  [SMALL_STATE(51)] = 1179,
  [SMALL_STATE(52)] = 1193,
  [SMALL_STATE(53)] = 1215,
  [SMALL_STATE(54)] = 1229,
  [SMALL_STATE(55)] = 1243,
  [SMALL_STATE(56)] = 1257,
  [SMALL_STATE(57)] = 1279,
  [SMALL_STATE(58)] = 1293,
  [SMALL_STATE(59)] = 1315,
  [SMALL_STATE(60)] = 1337,
  [SMALL_STATE(61)] = 1359,
  [SMALL_STATE(62)] = 1381,
  [SMALL_STATE(63)] = 1400,
  [SMALL_STATE(64)] = 1419,
  [SMALL_STATE(65)] = 1438,
  [SMALL_STATE(66)] = 1451,
  [SMALL_STATE(67)] = 1464,
  [SMALL_STATE(68)] = 1483,
  [SMALL_STATE(69)] = 1502,
  [SMALL_STATE(70)] = 1515,
  [SMALL_STATE(71)] = 1528,
  [SMALL_STATE(72)] = 1547,
  [SMALL_STATE(73)] = 1560,
  [SMALL_STATE(74)] = 1573,
  [SMALL_STATE(75)] = 1586,
  [SMALL_STATE(76)] = 1605,
  [SMALL_STATE(77)] = 1624,
  [SMALL_STATE(78)] = 1635,
  [SMALL_STATE(79)] = 1648,
  [SMALL_STATE(80)] = 1658,
  [SMALL_STATE(81)] = 1668,
  [SMALL_STATE(82)] = 1678,
  [SMALL_STATE(83)] = 1688,
  [SMALL_STATE(84)] = 1698,
  [SMALL_STATE(85)] = 1708,
  [SMALL_STATE(86)] = 1718,
  [SMALL_STATE(87)] = 1728,
  [SMALL_STATE(88)] = 1738,
  [SMALL_STATE(89)] = 1750,
  [SMALL_STATE(90)] = 1761,
  [SMALL_STATE(91)] = 1772,
  [SMALL_STATE(92)] = 1776,
  [SMALL_STATE(93)] = 1780,
  [SMALL_STATE(94)] = 1784,
  [SMALL_STATE(95)] = 1788,
  [SMALL_STATE(96)] = 1792,
  [SMALL_STATE(97)] = 1796,
  [SMALL_STATE(98)] = 1800,
  [SMALL_STATE(99)] = 1804,
  [SMALL_STATE(100)] = 1808,
  [SMALL_STATE(101)] = 1812,
  [SMALL_STATE(102)] = 1816,
  [SMALL_STATE(103)] = 1820,
  [SMALL_STATE(104)] = 1824,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pattern, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(67),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pattern, 1),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pattern, 2),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_pattern_repeat1, 2),
  [27] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_pattern_repeat1, 2), SHIFT_REPEAT(55),
  [30] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_pattern_repeat1, 2), SHIFT_REPEAT(31),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_pattern_repeat1, 2), SHIFT_REPEAT(89),
  [36] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_pattern_repeat1, 2), SHIFT_REPEAT(12),
  [39] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_pattern_repeat1, 2), SHIFT_REPEAT(67),
  [42] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_pattern_repeat1, 2), SHIFT_REPEAT(68),
  [45] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_pattern_repeat1, 2), SHIFT_REPEAT(9),
  [48] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [52] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [54] = {.entry = {.count = 1, .reusable = false}}, SHIFT(76),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [68] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_capture_repeat1, 2), SHIFT_REPEAT(38),
  [71] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_capture_repeat1, 2), SHIFT_REPEAT(90),
  [74] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_capture_repeat1, 2), SHIFT_REPEAT(18),
  [77] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_capture_repeat1, 2), SHIFT_REPEAT(76),
  [80] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_capture_repeat1, 2), SHIFT_REPEAT(63),
  [83] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_capture_repeat1, 2), SHIFT_REPEAT(8),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_capture_repeat1, 2),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_negated_set, 3),
  [90] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_negated_set, 3),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_capture, 3),
  [102] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_capture, 3),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_character, 1),
  [110] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_character, 1),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_class, 1),
  [116] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_class, 1),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_set, 3),
  [122] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_set, 3),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_capture, 2),
  [134] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_capture, 2),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_negated_set, 4),
  [144] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_negated_set, 4),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_set, 4),
  [152] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_set, 4),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [162] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__raw_character, 1),
  [164] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__raw_character, 1),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__class, 2),
  [170] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__class, 2),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_balanced_match, 3, .production_id = 2),
  [174] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_balanced_match, 3, .production_id = 2),
  [176] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_frontier_pattern, 2),
  [178] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_frontier_pattern, 2),
  [180] = {.entry = {.count = 1, .reusable = false}}, SHIFT(81),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [188] = {.entry = {.count = 1, .reusable = false}}, SHIFT(77),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [194] = {.entry = {.count = 1, .reusable = false}}, SHIFT(85),
  [196] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_capture, 4),
  [198] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_capture, 4),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [202] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_anchor_end, 1),
  [204] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_pattern_repeat1, 1, .production_id = 1),
  [206] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_pattern_repeat1, 1, .production_id = 1),
  [208] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_set_repeat1, 2), SHIFT_REPEAT(81),
  [211] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_set_repeat1, 2), SHIFT_REPEAT(79),
  [214] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_set_repeat1, 2), SHIFT_REPEAT(13),
  [217] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_set_repeat1, 2),
  [219] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_class, 2),
  [221] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_class, 2),
  [223] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_negated_set_repeat1, 2), SHIFT_REPEAT(77),
  [226] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_negated_set_repeat1, 2), SHIFT_REPEAT(21),
  [229] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_negated_set_repeat1, 2),
  [231] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_negated_set_repeat1, 2), SHIFT_REPEAT(85),
  [234] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_shortest_zero_or_more, 1),
  [236] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_shortest_zero_or_more, 1),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [240] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_character, 2),
  [242] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_character, 2),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [252] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_negated_set_repeat1, 1, .production_id = 1),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [256] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_negated_set_repeat1, 1, .production_id = 1),
  [258] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_set_repeat1, 1, .production_id = 1),
  [260] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_set_repeat1, 1, .production_id = 1),
  [262] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_range, 3, .dynamic_precedence = 1, .production_id = 3),
  [264] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_range, 3, .dynamic_precedence = 1, .production_id = 3),
  [266] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_set_repeat1, 1, .production_id = 1), SHIFT(97),
  [269] = {.entry = {.count = 1, .reusable = false}}, SHIFT(64),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [273] = {.entry = {.count = 1, .reusable = false}}, SHIFT(75),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [279] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [281] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [285] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [289] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [291] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [293] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pattern, 3),
  [295] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [297] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [299] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_luap(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
