#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 13
#define STATE_COUNT 95
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 47
#define ALIAS_COUNT 0
#define TOKEN_COUNT 30
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 4
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define PRODUCTION_ID_COUNT 4

enum {
  anon_sym_DOLLAR = 1,
  anon_sym_CARET = 2,
  aux_sym__raw_character_token1 = 3,
  anon_sym_DOT = 4,
  sym_all_letters_char = 5,
  sym_control_char = 6,
  sym_digit_char = 7,
  sym_printable_char = 8,
  sym_lowercase_char = 9,
  sym_punctuation_char = 10,
  sym_space_char = 11,
  sym_uppercase_char = 12,
  sym_alphanumeric_char = 13,
  sym_hexadecimal_char = 14,
  sym_escape_char = 15,
  sym_capture_index = 16,
  anon_sym_b = 17,
  aux_sym_balanced_match_token1 = 18,
  anon_sym_PERCENTf = 19,
  sym_zero_or_more = 20,
  anon_sym_DASH = 21,
  sym_one_or_more = 22,
  sym_zero_or_one = 23,
  anon_sym_PERCENT = 24,
  aux_sym_range_token1 = 25,
  anon_sym_LBRACK = 26,
  anon_sym_LPAREN = 27,
  anon_sym_RBRACK = 28,
  anon_sym_RPAREN = 29,
  sym_pattern = 30,
  sym_anchor_begin = 31,
  sym_anchor_end = 32,
  sym__raw_character = 33,
  sym_character = 34,
  sym_balanced_match = 35,
  sym_frontier_pattern = 36,
  sym_shortest_zero_or_more = 37,
  sym__class = 38,
  sym_class = 39,
  sym_range = 40,
  sym_set = 41,
  sym_negated_set = 42,
  sym_capture = 43,
  aux_sym_pattern_repeat1 = 44,
  aux_sym_set_repeat1 = 45,
  aux_sym_capture_repeat1 = 46,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_DOLLAR] = "$",
  [anon_sym_CARET] = "^",
  [aux_sym__raw_character_token1] = "_raw_character_token1",
  [anon_sym_DOT] = ".",
  [sym_all_letters_char] = "all_letters_char",
  [sym_control_char] = "control_char",
  [sym_digit_char] = "digit_char",
  [sym_printable_char] = "printable_char",
  [sym_lowercase_char] = "lowercase_char",
  [sym_punctuation_char] = "punctuation_char",
  [sym_space_char] = "space_char",
  [sym_uppercase_char] = "uppercase_char",
  [sym_alphanumeric_char] = "alphanumeric_char",
  [sym_hexadecimal_char] = "hexadecimal_char",
  [sym_escape_char] = "escape_char",
  [sym_capture_index] = "capture_index",
  [anon_sym_b] = "b",
  [aux_sym_balanced_match_token1] = "character",
  [anon_sym_PERCENTf] = "%f",
  [sym_zero_or_more] = "zero_or_more",
  [anon_sym_DASH] = "-",
  [sym_one_or_more] = "one_or_more",
  [sym_zero_or_one] = "zero_or_one",
  [anon_sym_PERCENT] = "%",
  [aux_sym_range_token1] = "character",
  [anon_sym_LBRACK] = "[",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RBRACK] = "]",
  [anon_sym_RPAREN] = ")",
  [sym_pattern] = "pattern",
  [sym_anchor_begin] = "anchor_begin",
  [sym_anchor_end] = "anchor_end",
  [sym__raw_character] = "_raw_character",
  [sym_character] = "character",
  [sym_balanced_match] = "balanced_match",
  [sym_frontier_pattern] = "frontier_pattern",
  [sym_shortest_zero_or_more] = "shortest_zero_or_more",
  [sym__class] = "_class",
  [sym_class] = "class",
  [sym_range] = "range",
  [sym_set] = "set",
  [sym_negated_set] = "negated_set",
  [sym_capture] = "capture",
  [aux_sym_pattern_repeat1] = "pattern_repeat1",
  [aux_sym_set_repeat1] = "set_repeat1",
  [aux_sym_capture_repeat1] = "capture_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_DOLLAR] = anon_sym_DOLLAR,
  [anon_sym_CARET] = anon_sym_CARET,
  [aux_sym__raw_character_token1] = aux_sym__raw_character_token1,
  [anon_sym_DOT] = anon_sym_DOT,
  [sym_all_letters_char] = sym_all_letters_char,
  [sym_control_char] = sym_control_char,
  [sym_digit_char] = sym_digit_char,
  [sym_printable_char] = sym_printable_char,
  [sym_lowercase_char] = sym_lowercase_char,
  [sym_punctuation_char] = sym_punctuation_char,
  [sym_space_char] = sym_space_char,
  [sym_uppercase_char] = sym_uppercase_char,
  [sym_alphanumeric_char] = sym_alphanumeric_char,
  [sym_hexadecimal_char] = sym_hexadecimal_char,
  [sym_escape_char] = sym_escape_char,
  [sym_capture_index] = sym_capture_index,
  [anon_sym_b] = anon_sym_b,
  [aux_sym_balanced_match_token1] = sym_character,
  [anon_sym_PERCENTf] = anon_sym_PERCENTf,
  [sym_zero_or_more] = sym_zero_or_more,
  [anon_sym_DASH] = anon_sym_DASH,
  [sym_one_or_more] = sym_one_or_more,
  [sym_zero_or_one] = sym_zero_or_one,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [aux_sym_range_token1] = sym_character,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_pattern] = sym_pattern,
  [sym_anchor_begin] = sym_anchor_begin,
  [sym_anchor_end] = sym_anchor_end,
  [sym__raw_character] = sym__raw_character,
  [sym_character] = sym_character,
  [sym_balanced_match] = sym_balanced_match,
  [sym_frontier_pattern] = sym_frontier_pattern,
  [sym_shortest_zero_or_more] = sym_shortest_zero_or_more,
  [sym__class] = sym__class,
  [sym_class] = sym_class,
  [sym_range] = sym_range,
  [sym_set] = sym_set,
  [sym_negated_set] = sym_negated_set,
  [sym_capture] = sym_capture,
  [aux_sym_pattern_repeat1] = aux_sym_pattern_repeat1,
  [aux_sym_set_repeat1] = aux_sym_set_repeat1,
  [aux_sym_capture_repeat1] = aux_sym_capture_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_DOLLAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_CARET] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__raw_character_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [sym_all_letters_char] = {
    .visible = true,
    .named = true,
  },
  [sym_control_char] = {
    .visible = true,
    .named = true,
  },
  [sym_digit_char] = {
    .visible = true,
    .named = true,
  },
  [sym_printable_char] = {
    .visible = true,
    .named = true,
  },
  [sym_lowercase_char] = {
    .visible = true,
    .named = true,
  },
  [sym_punctuation_char] = {
    .visible = true,
    .named = true,
  },
  [sym_space_char] = {
    .visible = true,
    .named = true,
  },
  [sym_uppercase_char] = {
    .visible = true,
    .named = true,
  },
  [sym_alphanumeric_char] = {
    .visible = true,
    .named = true,
  },
  [sym_hexadecimal_char] = {
    .visible = true,
    .named = true,
  },
  [sym_escape_char] = {
    .visible = true,
    .named = true,
  },
  [sym_capture_index] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_b] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_balanced_match_token1] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_PERCENTf] = {
    .visible = true,
    .named = false,
  },
  [sym_zero_or_more] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [sym_one_or_more] = {
    .visible = true,
    .named = true,
  },
  [sym_zero_or_one] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_range_token1] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_pattern] = {
    .visible = true,
    .named = true,
  },
  [sym_anchor_begin] = {
    .visible = true,
    .named = true,
  },
  [sym_anchor_end] = {
    .visible = true,
    .named = true,
  },
  [sym__raw_character] = {
    .visible = false,
    .named = true,
  },
  [sym_character] = {
    .visible = true,
    .named = true,
  },
  [sym_balanced_match] = {
    .visible = true,
    .named = true,
  },
  [sym_frontier_pattern] = {
    .visible = true,
    .named = true,
  },
  [sym_shortest_zero_or_more] = {
    .visible = true,
    .named = true,
  },
  [sym__class] = {
    .visible = false,
    .named = true,
  },
  [sym_class] = {
    .visible = true,
    .named = true,
  },
  [sym_range] = {
    .visible = true,
    .named = true,
  },
  [sym_set] = {
    .visible = true,
    .named = true,
  },
  [sym_negated_set] = {
    .visible = true,
    .named = true,
  },
  [sym_capture] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_pattern_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_set_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_capture_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_first = 1,
  field_from = 2,
  field_last = 3,
  field_to = 4,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_first] = "first",
  [field_from] = "from",
  [field_last] = "last",
  [field_to] = "to",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [2] = {.index = 0, .length = 2},
  [3] = {.index = 2, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_first, 1},
    {field_last, 2},
  [2] =
    {field_from, 0},
    {field_to, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [0] = sym_character,
  },
  [3] = {
    [0] = sym_character,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  sym__raw_character, 2,
    sym__raw_character,
    sym_character,
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 7,
  [10] = 8,
  [11] = 11,
  [12] = 11,
  [13] = 11,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 15,
  [19] = 19,
  [20] = 16,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 17,
  [25] = 15,
  [26] = 21,
  [27] = 14,
  [28] = 19,
  [29] = 16,
  [30] = 15,
  [31] = 31,
  [32] = 16,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 33,
  [37] = 34,
  [38] = 31,
  [39] = 35,
  [40] = 22,
  [41] = 23,
  [42] = 42,
  [43] = 43,
  [44] = 43,
  [45] = 43,
  [46] = 46,
  [47] = 42,
  [48] = 48,
  [49] = 43,
  [50] = 48,
  [51] = 48,
  [52] = 42,
  [53] = 42,
  [54] = 48,
  [55] = 55,
  [56] = 55,
  [57] = 55,
  [58] = 55,
  [59] = 23,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 22,
  [69] = 22,
  [70] = 62,
  [71] = 63,
  [72] = 64,
  [73] = 23,
  [74] = 65,
  [75] = 66,
  [76] = 33,
  [77] = 77,
  [78] = 34,
  [79] = 31,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 82,
  [84] = 84,
  [85] = 84,
  [86] = 86,
  [87] = 87,
  [88] = 84,
  [89] = 89,
  [90] = 89,
  [91] = 91,
  [92] = 89,
  [93] = 93,
  [94] = 94,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(14);
      if (lookahead == '\n') SKIP(13)
      if (lookahead == '$') ADVANCE(15);
      if (lookahead == '%') ADVANCE(39);
      if (lookahead == '(') ADVANCE(43);
      if (lookahead == ')') ADVANCE(45);
      if (lookahead == '*') ADVANCE(34);
      if (lookahead == '+') ADVANCE(36);
      if (lookahead == '-') ADVANCE(35);
      if (lookahead == '.') ADVANCE(18);
      if (lookahead == '?') ADVANCE(37);
      if (lookahead == '[') ADVANCE(42);
      if (lookahead == ']') ADVANCE(44);
      if (lookahead == '^') ADVANCE(16);
      if (lookahead == 'a') ADVANCE(19);
      if (lookahead == 'b') ADVANCE(31);
      if (lookahead == 'c') ADVANCE(20);
      if (lookahead == 'd') ADVANCE(21);
      if (lookahead == 'g') ADVANCE(22);
      if (lookahead == 'l') ADVANCE(23);
      if (lookahead == 'p') ADVANCE(24);
      if (lookahead == 's') ADVANCE(25);
      if (lookahead == 'u') ADVANCE(26);
      if (lookahead == 'w') ADVANCE(27);
      if (lookahead == 'x') ADVANCE(28);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(17);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(17);
      if (lookahead != 0) ADVANCE(17);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(6)
      if (lookahead == '%') ADVANCE(39);
      if (lookahead == '(') ADVANCE(43);
      if (lookahead == ')') ADVANCE(45);
      if (lookahead == '*') ADVANCE(34);
      if (lookahead == '+') ADVANCE(36);
      if (lookahead == '-') ADVANCE(35);
      if (lookahead == '.') ADVANCE(18);
      if (lookahead == '?') ADVANCE(37);
      if (lookahead == '[') ADVANCE(42);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(17);
      if (lookahead != 0) ADVANCE(17);
      END_STATE();
    case 2:
      if (lookahead == '\n') SKIP(6)
      if (lookahead == '%') ADVANCE(39);
      if (lookahead == '(') ADVANCE(43);
      if (lookahead == ')') ADVANCE(45);
      if (lookahead == '.') ADVANCE(18);
      if (lookahead == '[') ADVANCE(42);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(17);
      if (lookahead != 0) ADVANCE(17);
      END_STATE();
    case 3:
      if (lookahead == '\n') SKIP(6)
      if (lookahead == '%') ADVANCE(38);
      if (lookahead == '(') ADVANCE(43);
      if (lookahead == '-') ADVANCE(35);
      if (lookahead == '.') ADVANCE(18);
      if (lookahead == ']') ADVANCE(44);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(17);
      if (lookahead != 0 &&
          lookahead != '[') ADVANCE(17);
      END_STATE();
    case 4:
      if (lookahead == '\n') SKIP(6)
      if (lookahead == '%') ADVANCE(38);
      if (lookahead == '(') ADVANCE(43);
      if (lookahead == '-') ADVANCE(35);
      if (lookahead == '.') ADVANCE(18);
      if (lookahead == '^') ADVANCE(16);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(17);
      if (lookahead != 0 &&
          lookahead != '[') ADVANCE(17);
      END_STATE();
    case 5:
      if (lookahead == '\n') SKIP(6)
      if (lookahead == '%') ADVANCE(38);
      if (lookahead == '(') ADVANCE(43);
      if (lookahead == '-') ADVANCE(35);
      if (lookahead == '.') ADVANCE(18);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(17);
      if (lookahead != 0 &&
          lookahead != '[') ADVANCE(17);
      END_STATE();
    case 6:
      if (lookahead == '.') ADVANCE(18);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(6)
      END_STATE();
    case 7:
      if (lookahead == 'a') ADVANCE(19);
      if (lookahead == 'b') ADVANCE(31);
      if (lookahead == 'c') ADVANCE(20);
      if (lookahead == 'd') ADVANCE(21);
      if (lookahead == 'g') ADVANCE(22);
      if (lookahead == 'l') ADVANCE(23);
      if (lookahead == 'p') ADVANCE(24);
      if (lookahead == 's') ADVANCE(25);
      if (lookahead == 'u') ADVANCE(26);
      if (lookahead == 'w') ADVANCE(27);
      if (lookahead == 'x') ADVANCE(28);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(30);
      if (lookahead != 0 &&
          lookahead != '0' &&
          (lookahead < 'A' || 'Z' < lookahead) &&
          lookahead != '_' &&
          (lookahead < 'e' || 'z' < lookahead)) ADVANCE(29);
      END_STATE();
    case 8:
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(41);
      if (lookahead != 0 &&
          lookahead != ']') ADVANCE(40);
      END_STATE();
    case 9:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(32);
      END_STATE();
    case 10:
      if (eof) ADVANCE(14);
      if (lookahead == '\n') SKIP(13)
      if (lookahead == '$') ADVANCE(15);
      if (lookahead == '%') ADVANCE(39);
      if (lookahead == '(') ADVANCE(43);
      if (lookahead == '*') ADVANCE(34);
      if (lookahead == '+') ADVANCE(36);
      if (lookahead == '-') ADVANCE(35);
      if (lookahead == '.') ADVANCE(18);
      if (lookahead == '?') ADVANCE(37);
      if (lookahead == '[') ADVANCE(42);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(17);
      if (lookahead != 0) ADVANCE(17);
      END_STATE();
    case 11:
      if (eof) ADVANCE(14);
      if (lookahead == '\n') SKIP(13)
      if (lookahead == '$') ADVANCE(15);
      if (lookahead == '%') ADVANCE(39);
      if (lookahead == '(') ADVANCE(43);
      if (lookahead == '.') ADVANCE(18);
      if (lookahead == '[') ADVANCE(42);
      if (lookahead == '^') ADVANCE(16);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(17);
      if (lookahead != 0) ADVANCE(17);
      END_STATE();
    case 12:
      if (eof) ADVANCE(14);
      if (lookahead == '\n') SKIP(13)
      if (lookahead == '$') ADVANCE(15);
      if (lookahead == '%') ADVANCE(39);
      if (lookahead == '(') ADVANCE(43);
      if (lookahead == '.') ADVANCE(18);
      if (lookahead == '[') ADVANCE(42);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(17);
      if (lookahead != 0) ADVANCE(17);
      END_STATE();
    case 13:
      if (eof) ADVANCE(14);
      if (lookahead == '.') ADVANCE(18);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(13)
      END_STATE();
    case 14:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_DOLLAR);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_CARET);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(aux_sym__raw_character_token1);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_all_letters_char);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_control_char);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_digit_char);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_printable_char);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_lowercase_char);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_punctuation_char);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_space_char);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_uppercase_char);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_alphanumeric_char);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_hexadecimal_char);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_escape_char);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_capture_index);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_b);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym_balanced_match_token1);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_PERCENTf);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_zero_or_more);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_one_or_more);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_zero_or_one);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      if (lookahead == 'f') ADVANCE(33);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(aux_sym_range_token1);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(aux_sym_range_token1);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(41);
      if (lookahead != 0 &&
          lookahead != ']') ADVANCE(40);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 11},
  [2] = {.lex_state = 12},
  [3] = {.lex_state = 12},
  [4] = {.lex_state = 12},
  [5] = {.lex_state = 12},
  [6] = {.lex_state = 2},
  [7] = {.lex_state = 2},
  [8] = {.lex_state = 2},
  [9] = {.lex_state = 2},
  [10] = {.lex_state = 2},
  [11] = {.lex_state = 7},
  [12] = {.lex_state = 7},
  [13] = {.lex_state = 7},
  [14] = {.lex_state = 10},
  [15] = {.lex_state = 10},
  [16] = {.lex_state = 10},
  [17] = {.lex_state = 10},
  [18] = {.lex_state = 10},
  [19] = {.lex_state = 10},
  [20] = {.lex_state = 10},
  [21] = {.lex_state = 10},
  [22] = {.lex_state = 10},
  [23] = {.lex_state = 10},
  [24] = {.lex_state = 1},
  [25] = {.lex_state = 1},
  [26] = {.lex_state = 1},
  [27] = {.lex_state = 1},
  [28] = {.lex_state = 1},
  [29] = {.lex_state = 1},
  [30] = {.lex_state = 1},
  [31] = {.lex_state = 10},
  [32] = {.lex_state = 1},
  [33] = {.lex_state = 10},
  [34] = {.lex_state = 10},
  [35] = {.lex_state = 10},
  [36] = {.lex_state = 1},
  [37] = {.lex_state = 1},
  [38] = {.lex_state = 1},
  [39] = {.lex_state = 1},
  [40] = {.lex_state = 1},
  [41] = {.lex_state = 1},
  [42] = {.lex_state = 3},
  [43] = {.lex_state = 4},
  [44] = {.lex_state = 4},
  [45] = {.lex_state = 4},
  [46] = {.lex_state = 3},
  [47] = {.lex_state = 3},
  [48] = {.lex_state = 3},
  [49] = {.lex_state = 4},
  [50] = {.lex_state = 3},
  [51] = {.lex_state = 3},
  [52] = {.lex_state = 3},
  [53] = {.lex_state = 3},
  [54] = {.lex_state = 3},
  [55] = {.lex_state = 5},
  [56] = {.lex_state = 5},
  [57] = {.lex_state = 5},
  [58] = {.lex_state = 5},
  [59] = {.lex_state = 12},
  [60] = {.lex_state = 12},
  [61] = {.lex_state = 12},
  [62] = {.lex_state = 12},
  [63] = {.lex_state = 12},
  [64] = {.lex_state = 12},
  [65] = {.lex_state = 12},
  [66] = {.lex_state = 12},
  [67] = {.lex_state = 12},
  [68] = {.lex_state = 12},
  [69] = {.lex_state = 2},
  [70] = {.lex_state = 2},
  [71] = {.lex_state = 2},
  [72] = {.lex_state = 2},
  [73] = {.lex_state = 2},
  [74] = {.lex_state = 2},
  [75] = {.lex_state = 2},
  [76] = {.lex_state = 3},
  [77] = {.lex_state = 3},
  [78] = {.lex_state = 3},
  [79] = {.lex_state = 3},
  [80] = {.lex_state = 3},
  [81] = {.lex_state = 3},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 9},
  [85] = {.lex_state = 9},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 9},
  [89] = {.lex_state = 9},
  [90] = {.lex_state = 9},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 9},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 8},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_DOLLAR] = ACTIONS(1),
    [anon_sym_CARET] = ACTIONS(1),
    [aux_sym__raw_character_token1] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [sym_all_letters_char] = ACTIONS(1),
    [sym_control_char] = ACTIONS(1),
    [sym_digit_char] = ACTIONS(1),
    [sym_printable_char] = ACTIONS(1),
    [sym_lowercase_char] = ACTIONS(1),
    [sym_punctuation_char] = ACTIONS(1),
    [sym_space_char] = ACTIONS(1),
    [sym_uppercase_char] = ACTIONS(1),
    [sym_alphanumeric_char] = ACTIONS(1),
    [sym_hexadecimal_char] = ACTIONS(1),
    [sym_capture_index] = ACTIONS(1),
    [anon_sym_b] = ACTIONS(1),
    [anon_sym_PERCENTf] = ACTIONS(1),
    [sym_zero_or_more] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [sym_one_or_more] = ACTIONS(1),
    [sym_zero_or_one] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
  },
  [1] = {
    [sym_pattern] = STATE(93),
    [sym_anchor_begin] = STATE(3),
    [sym_anchor_end] = STATE(91),
    [sym__raw_character] = STATE(19),
    [sym_character] = STATE(2),
    [sym_frontier_pattern] = STATE(14),
    [sym__class] = STATE(14),
    [sym_class] = STATE(2),
    [sym_set] = STATE(2),
    [sym_negated_set] = STATE(2),
    [sym_capture] = STATE(2),
    [aux_sym_pattern_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_DOLLAR] = ACTIONS(5),
    [anon_sym_CARET] = ACTIONS(7),
    [aux_sym__raw_character_token1] = ACTIONS(9),
    [anon_sym_DOT] = ACTIONS(9),
    [anon_sym_PERCENTf] = ACTIONS(11),
    [anon_sym_PERCENT] = ACTIONS(13),
    [anon_sym_LBRACK] = ACTIONS(15),
    [anon_sym_LPAREN] = ACTIONS(17),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 11,
    ACTIONS(5), 1,
      anon_sym_DOLLAR,
    ACTIONS(11), 1,
      anon_sym_PERCENTf,
    ACTIONS(13), 1,
      anon_sym_PERCENT,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      ts_builtin_sym_end,
    STATE(19), 1,
      sym__raw_character,
    STATE(86), 1,
      sym_anchor_end,
    ACTIONS(9), 2,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
    STATE(14), 2,
      sym_frontier_pattern,
      sym__class,
    STATE(5), 6,
      sym_character,
      sym_class,
      sym_set,
      sym_negated_set,
      sym_capture,
      aux_sym_pattern_repeat1,
  [41] = 11,
    ACTIONS(5), 1,
      anon_sym_DOLLAR,
    ACTIONS(11), 1,
      anon_sym_PERCENTf,
    ACTIONS(13), 1,
      anon_sym_PERCENT,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      ts_builtin_sym_end,
    STATE(19), 1,
      sym__raw_character,
    STATE(86), 1,
      sym_anchor_end,
    ACTIONS(9), 2,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
    STATE(14), 2,
      sym_frontier_pattern,
      sym__class,
    STATE(4), 6,
      sym_character,
      sym_class,
      sym_set,
      sym_negated_set,
      sym_capture,
      aux_sym_pattern_repeat1,
  [82] = 11,
    ACTIONS(5), 1,
      anon_sym_DOLLAR,
    ACTIONS(11), 1,
      anon_sym_PERCENTf,
    ACTIONS(13), 1,
      anon_sym_PERCENT,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(21), 1,
      ts_builtin_sym_end,
    STATE(19), 1,
      sym__raw_character,
    STATE(87), 1,
      sym_anchor_end,
    ACTIONS(9), 2,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
    STATE(14), 2,
      sym_frontier_pattern,
      sym__class,
    STATE(5), 6,
      sym_character,
      sym_class,
      sym_set,
      sym_negated_set,
      sym_capture,
      aux_sym_pattern_repeat1,
  [123] = 10,
    ACTIONS(23), 1,
      ts_builtin_sym_end,
    ACTIONS(25), 1,
      anon_sym_DOLLAR,
    ACTIONS(31), 1,
      anon_sym_PERCENTf,
    ACTIONS(34), 1,
      anon_sym_PERCENT,
    ACTIONS(37), 1,
      anon_sym_LBRACK,
    ACTIONS(40), 1,
      anon_sym_LPAREN,
    STATE(19), 1,
      sym__raw_character,
    ACTIONS(28), 2,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
    STATE(14), 2,
      sym_frontier_pattern,
      sym__class,
    STATE(5), 6,
      sym_character,
      sym_class,
      sym_set,
      sym_negated_set,
      sym_capture,
      aux_sym_pattern_repeat1,
  [161] = 9,
    ACTIONS(46), 1,
      anon_sym_PERCENTf,
    ACTIONS(49), 1,
      anon_sym_PERCENT,
    ACTIONS(52), 1,
      anon_sym_LBRACK,
    ACTIONS(55), 1,
      anon_sym_LPAREN,
    ACTIONS(58), 1,
      anon_sym_RPAREN,
    STATE(28), 1,
      sym__raw_character,
    ACTIONS(43), 2,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
    STATE(27), 2,
      sym_frontier_pattern,
      sym__class,
    STATE(6), 6,
      sym_character,
      sym_class,
      sym_set,
      sym_negated_set,
      sym_capture,
      aux_sym_capture_repeat1,
  [196] = 9,
    ACTIONS(62), 1,
      anon_sym_PERCENTf,
    ACTIONS(64), 1,
      anon_sym_PERCENT,
    ACTIONS(66), 1,
      anon_sym_LBRACK,
    ACTIONS(68), 1,
      anon_sym_LPAREN,
    ACTIONS(70), 1,
      anon_sym_RPAREN,
    STATE(28), 1,
      sym__raw_character,
    ACTIONS(60), 2,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
    STATE(27), 2,
      sym_frontier_pattern,
      sym__class,
    STATE(8), 6,
      sym_character,
      sym_class,
      sym_set,
      sym_negated_set,
      sym_capture,
      aux_sym_capture_repeat1,
  [231] = 9,
    ACTIONS(62), 1,
      anon_sym_PERCENTf,
    ACTIONS(64), 1,
      anon_sym_PERCENT,
    ACTIONS(66), 1,
      anon_sym_LBRACK,
    ACTIONS(68), 1,
      anon_sym_LPAREN,
    ACTIONS(72), 1,
      anon_sym_RPAREN,
    STATE(28), 1,
      sym__raw_character,
    ACTIONS(60), 2,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
    STATE(27), 2,
      sym_frontier_pattern,
      sym__class,
    STATE(6), 6,
      sym_character,
      sym_class,
      sym_set,
      sym_negated_set,
      sym_capture,
      aux_sym_capture_repeat1,
  [266] = 9,
    ACTIONS(62), 1,
      anon_sym_PERCENTf,
    ACTIONS(64), 1,
      anon_sym_PERCENT,
    ACTIONS(66), 1,
      anon_sym_LBRACK,
    ACTIONS(68), 1,
      anon_sym_LPAREN,
    ACTIONS(74), 1,
      anon_sym_RPAREN,
    STATE(28), 1,
      sym__raw_character,
    ACTIONS(60), 2,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
    STATE(27), 2,
      sym_frontier_pattern,
      sym__class,
    STATE(10), 6,
      sym_character,
      sym_class,
      sym_set,
      sym_negated_set,
      sym_capture,
      aux_sym_capture_repeat1,
  [301] = 9,
    ACTIONS(62), 1,
      anon_sym_PERCENTf,
    ACTIONS(64), 1,
      anon_sym_PERCENT,
    ACTIONS(66), 1,
      anon_sym_LBRACK,
    ACTIONS(68), 1,
      anon_sym_LPAREN,
    ACTIONS(76), 1,
      anon_sym_RPAREN,
    STATE(28), 1,
      sym__raw_character,
    ACTIONS(60), 2,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
    STATE(27), 2,
      sym_frontier_pattern,
      sym__class,
    STATE(6), 6,
      sym_character,
      sym_class,
      sym_set,
      sym_negated_set,
      sym_capture,
      aux_sym_capture_repeat1,
  [336] = 3,
    ACTIONS(80), 1,
      anon_sym_b,
    STATE(79), 1,
      sym_balanced_match,
    ACTIONS(78), 12,
      sym_all_letters_char,
      sym_control_char,
      sym_digit_char,
      sym_printable_char,
      sym_lowercase_char,
      sym_punctuation_char,
      sym_space_char,
      sym_uppercase_char,
      sym_alphanumeric_char,
      sym_hexadecimal_char,
      sym_escape_char,
      sym_capture_index,
  [357] = 3,
    ACTIONS(84), 1,
      anon_sym_b,
    STATE(31), 1,
      sym_balanced_match,
    ACTIONS(82), 12,
      sym_all_letters_char,
      sym_control_char,
      sym_digit_char,
      sym_printable_char,
      sym_lowercase_char,
      sym_punctuation_char,
      sym_space_char,
      sym_uppercase_char,
      sym_alphanumeric_char,
      sym_hexadecimal_char,
      sym_escape_char,
      sym_capture_index,
  [378] = 3,
    ACTIONS(88), 1,
      anon_sym_b,
    STATE(38), 1,
      sym_balanced_match,
    ACTIONS(86), 12,
      sym_all_letters_char,
      sym_control_char,
      sym_digit_char,
      sym_printable_char,
      sym_lowercase_char,
      sym_punctuation_char,
      sym_space_char,
      sym_uppercase_char,
      sym_alphanumeric_char,
      sym_hexadecimal_char,
      sym_escape_char,
      sym_capture_index,
  [399] = 5,
    ACTIONS(96), 1,
      anon_sym_DASH,
    STATE(64), 1,
      sym_shortest_zero_or_more,
    ACTIONS(92), 3,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
    ACTIONS(94), 3,
      sym_zero_or_more,
      sym_one_or_more,
      sym_zero_or_one,
    ACTIONS(90), 5,
      ts_builtin_sym_end,
      anon_sym_DOLLAR,
      anon_sym_PERCENTf,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
  [423] = 5,
    ACTIONS(96), 1,
      anon_sym_DASH,
    STATE(68), 1,
      sym_shortest_zero_or_more,
    ACTIONS(100), 3,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
    ACTIONS(102), 3,
      sym_zero_or_more,
      sym_one_or_more,
      sym_zero_or_one,
    ACTIONS(98), 5,
      ts_builtin_sym_end,
      anon_sym_DOLLAR,
      anon_sym_PERCENTf,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
  [447] = 5,
    ACTIONS(96), 1,
      anon_sym_DASH,
    STATE(59), 1,
      sym_shortest_zero_or_more,
    ACTIONS(106), 3,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
    ACTIONS(108), 3,
      sym_zero_or_more,
      sym_one_or_more,
      sym_zero_or_one,
    ACTIONS(104), 5,
      ts_builtin_sym_end,
      anon_sym_DOLLAR,
      anon_sym_PERCENTf,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
  [471] = 5,
    ACTIONS(96), 1,
      anon_sym_DASH,
    STATE(66), 1,
      sym_shortest_zero_or_more,
    ACTIONS(112), 3,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
    ACTIONS(114), 3,
      sym_zero_or_more,
      sym_one_or_more,
      sym_zero_or_one,
    ACTIONS(110), 5,
      ts_builtin_sym_end,
      anon_sym_DOLLAR,
      anon_sym_PERCENTf,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
  [495] = 3,
    STATE(22), 1,
      sym_shortest_zero_or_more,
    ACTIONS(100), 3,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
    ACTIONS(98), 9,
      ts_builtin_sym_end,
      anon_sym_DOLLAR,
      anon_sym_PERCENTf,
      sym_zero_or_more,
      anon_sym_DASH,
      sym_one_or_more,
      sym_zero_or_one,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
  [515] = 5,
    ACTIONS(96), 1,
      anon_sym_DASH,
    STATE(62), 1,
      sym_shortest_zero_or_more,
    ACTIONS(118), 3,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
    ACTIONS(120), 3,
      sym_zero_or_more,
      sym_one_or_more,
      sym_zero_or_one,
    ACTIONS(116), 5,
      ts_builtin_sym_end,
      anon_sym_DOLLAR,
      anon_sym_PERCENTf,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
  [539] = 3,
    STATE(23), 1,
      sym_shortest_zero_or_more,
    ACTIONS(106), 3,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
    ACTIONS(104), 9,
      ts_builtin_sym_end,
      anon_sym_DOLLAR,
      anon_sym_PERCENTf,
      sym_zero_or_more,
      anon_sym_DASH,
      sym_one_or_more,
      sym_zero_or_one,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
  [559] = 5,
    ACTIONS(96), 1,
      anon_sym_DASH,
    STATE(65), 1,
      sym_shortest_zero_or_more,
    ACTIONS(124), 3,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
    ACTIONS(126), 3,
      sym_zero_or_more,
      sym_one_or_more,
      sym_zero_or_one,
    ACTIONS(122), 5,
      ts_builtin_sym_end,
      anon_sym_DOLLAR,
      anon_sym_PERCENTf,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
  [583] = 2,
    ACTIONS(130), 3,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
    ACTIONS(128), 9,
      ts_builtin_sym_end,
      anon_sym_DOLLAR,
      anon_sym_PERCENTf,
      sym_zero_or_more,
      anon_sym_DASH,
      sym_one_or_more,
      sym_zero_or_one,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
  [600] = 2,
    ACTIONS(134), 3,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
    ACTIONS(132), 9,
      ts_builtin_sym_end,
      anon_sym_DOLLAR,
      anon_sym_PERCENTf,
      sym_zero_or_more,
      anon_sym_DASH,
      sym_one_or_more,
      sym_zero_or_one,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
  [617] = 5,
    ACTIONS(138), 1,
      anon_sym_DASH,
    STATE(75), 1,
      sym_shortest_zero_or_more,
    ACTIONS(112), 3,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
    ACTIONS(136), 3,
      sym_zero_or_more,
      sym_one_or_more,
      sym_zero_or_one,
    ACTIONS(110), 4,
      anon_sym_PERCENTf,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [640] = 5,
    ACTIONS(138), 1,
      anon_sym_DASH,
    STATE(69), 1,
      sym_shortest_zero_or_more,
    ACTIONS(100), 3,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
    ACTIONS(140), 3,
      sym_zero_or_more,
      sym_one_or_more,
      sym_zero_or_one,
    ACTIONS(98), 4,
      anon_sym_PERCENTf,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [663] = 5,
    ACTIONS(138), 1,
      anon_sym_DASH,
    STATE(74), 1,
      sym_shortest_zero_or_more,
    ACTIONS(124), 3,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
    ACTIONS(142), 3,
      sym_zero_or_more,
      sym_one_or_more,
      sym_zero_or_one,
    ACTIONS(122), 4,
      anon_sym_PERCENTf,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [686] = 5,
    ACTIONS(138), 1,
      anon_sym_DASH,
    STATE(72), 1,
      sym_shortest_zero_or_more,
    ACTIONS(92), 3,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
    ACTIONS(144), 3,
      sym_zero_or_more,
      sym_one_or_more,
      sym_zero_or_one,
    ACTIONS(90), 4,
      anon_sym_PERCENTf,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [709] = 5,
    ACTIONS(138), 1,
      anon_sym_DASH,
    STATE(70), 1,
      sym_shortest_zero_or_more,
    ACTIONS(118), 3,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
    ACTIONS(146), 3,
      sym_zero_or_more,
      sym_one_or_more,
      sym_zero_or_one,
    ACTIONS(116), 4,
      anon_sym_PERCENTf,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [732] = 5,
    ACTIONS(138), 1,
      anon_sym_DASH,
    STATE(73), 1,
      sym_shortest_zero_or_more,
    ACTIONS(106), 3,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
    ACTIONS(148), 3,
      sym_zero_or_more,
      sym_one_or_more,
      sym_zero_or_one,
    ACTIONS(104), 4,
      anon_sym_PERCENTf,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [755] = 3,
    STATE(40), 1,
      sym_shortest_zero_or_more,
    ACTIONS(100), 3,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
    ACTIONS(98), 8,
      anon_sym_PERCENTf,
      sym_zero_or_more,
      anon_sym_DASH,
      sym_one_or_more,
      sym_zero_or_one,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [774] = 2,
    ACTIONS(152), 3,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
    ACTIONS(150), 9,
      ts_builtin_sym_end,
      anon_sym_DOLLAR,
      anon_sym_PERCENTf,
      sym_zero_or_more,
      anon_sym_DASH,
      sym_one_or_more,
      sym_zero_or_one,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
  [791] = 3,
    STATE(41), 1,
      sym_shortest_zero_or_more,
    ACTIONS(106), 3,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
    ACTIONS(104), 8,
      anon_sym_PERCENTf,
      sym_zero_or_more,
      anon_sym_DASH,
      sym_one_or_more,
      sym_zero_or_one,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [810] = 2,
    ACTIONS(156), 3,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
    ACTIONS(154), 9,
      ts_builtin_sym_end,
      anon_sym_DOLLAR,
      anon_sym_PERCENTf,
      sym_zero_or_more,
      anon_sym_DASH,
      sym_one_or_more,
      sym_zero_or_one,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
  [827] = 2,
    ACTIONS(160), 3,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
    ACTIONS(158), 9,
      ts_builtin_sym_end,
      anon_sym_DOLLAR,
      anon_sym_PERCENTf,
      sym_zero_or_more,
      anon_sym_DASH,
      sym_one_or_more,
      sym_zero_or_one,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
  [844] = 2,
    ACTIONS(164), 3,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
    ACTIONS(162), 9,
      ts_builtin_sym_end,
      anon_sym_DOLLAR,
      anon_sym_PERCENTf,
      sym_zero_or_more,
      anon_sym_DASH,
      sym_one_or_more,
      sym_zero_or_one,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
  [861] = 2,
    ACTIONS(156), 3,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
    ACTIONS(154), 8,
      anon_sym_PERCENTf,
      sym_zero_or_more,
      anon_sym_DASH,
      sym_one_or_more,
      sym_zero_or_one,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [877] = 2,
    ACTIONS(160), 3,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
    ACTIONS(158), 8,
      anon_sym_PERCENTf,
      sym_zero_or_more,
      anon_sym_DASH,
      sym_one_or_more,
      sym_zero_or_one,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [893] = 2,
    ACTIONS(152), 3,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
    ACTIONS(150), 8,
      anon_sym_PERCENTf,
      sym_zero_or_more,
      anon_sym_DASH,
      sym_one_or_more,
      sym_zero_or_one,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [909] = 2,
    ACTIONS(164), 3,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
    ACTIONS(162), 8,
      anon_sym_PERCENTf,
      sym_zero_or_more,
      anon_sym_DASH,
      sym_one_or_more,
      sym_zero_or_one,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [925] = 2,
    ACTIONS(130), 3,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
    ACTIONS(128), 8,
      anon_sym_PERCENTf,
      sym_zero_or_more,
      anon_sym_DASH,
      sym_one_or_more,
      sym_zero_or_one,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [941] = 2,
    ACTIONS(134), 3,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
    ACTIONS(132), 8,
      anon_sym_PERCENTf,
      sym_zero_or_more,
      anon_sym_DASH,
      sym_one_or_more,
      sym_zero_or_one,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [957] = 6,
    ACTIONS(170), 1,
      anon_sym_PERCENT,
    ACTIONS(172), 1,
      anon_sym_RBRACK,
    STATE(81), 1,
      sym__raw_character,
    ACTIONS(166), 2,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
    ACTIONS(168), 2,
      anon_sym_DASH,
      anon_sym_LPAREN,
    STATE(46), 3,
      sym__class,
      sym_range,
      aux_sym_set_repeat1,
  [980] = 6,
    ACTIONS(170), 1,
      anon_sym_PERCENT,
    ACTIONS(174), 1,
      anon_sym_CARET,
    STATE(81), 1,
      sym__raw_character,
    ACTIONS(166), 2,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
    ACTIONS(168), 2,
      anon_sym_DASH,
      anon_sym_LPAREN,
    STATE(47), 3,
      sym__class,
      sym_range,
      aux_sym_set_repeat1,
  [1003] = 6,
    ACTIONS(170), 1,
      anon_sym_PERCENT,
    ACTIONS(176), 1,
      anon_sym_CARET,
    STATE(81), 1,
      sym__raw_character,
    ACTIONS(166), 2,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
    ACTIONS(168), 2,
      anon_sym_DASH,
      anon_sym_LPAREN,
    STATE(53), 3,
      sym__class,
      sym_range,
      aux_sym_set_repeat1,
  [1026] = 6,
    ACTIONS(170), 1,
      anon_sym_PERCENT,
    ACTIONS(178), 1,
      anon_sym_CARET,
    STATE(81), 1,
      sym__raw_character,
    ACTIONS(166), 2,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
    ACTIONS(168), 2,
      anon_sym_DASH,
      anon_sym_LPAREN,
    STATE(52), 3,
      sym__class,
      sym_range,
      aux_sym_set_repeat1,
  [1049] = 6,
    ACTIONS(186), 1,
      anon_sym_PERCENT,
    ACTIONS(189), 1,
      anon_sym_RBRACK,
    STATE(81), 1,
      sym__raw_character,
    ACTIONS(180), 2,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
    ACTIONS(183), 2,
      anon_sym_DASH,
      anon_sym_LPAREN,
    STATE(46), 3,
      sym__class,
      sym_range,
      aux_sym_set_repeat1,
  [1072] = 6,
    ACTIONS(170), 1,
      anon_sym_PERCENT,
    ACTIONS(191), 1,
      anon_sym_RBRACK,
    STATE(81), 1,
      sym__raw_character,
    ACTIONS(166), 2,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
    ACTIONS(168), 2,
      anon_sym_DASH,
      anon_sym_LPAREN,
    STATE(46), 3,
      sym__class,
      sym_range,
      aux_sym_set_repeat1,
  [1095] = 6,
    ACTIONS(170), 1,
      anon_sym_PERCENT,
    ACTIONS(193), 1,
      anon_sym_RBRACK,
    STATE(81), 1,
      sym__raw_character,
    ACTIONS(166), 2,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
    ACTIONS(168), 2,
      anon_sym_DASH,
      anon_sym_LPAREN,
    STATE(46), 3,
      sym__class,
      sym_range,
      aux_sym_set_repeat1,
  [1118] = 6,
    ACTIONS(170), 1,
      anon_sym_PERCENT,
    ACTIONS(195), 1,
      anon_sym_CARET,
    STATE(81), 1,
      sym__raw_character,
    ACTIONS(166), 2,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
    ACTIONS(168), 2,
      anon_sym_DASH,
      anon_sym_LPAREN,
    STATE(42), 3,
      sym__class,
      sym_range,
      aux_sym_set_repeat1,
  [1141] = 6,
    ACTIONS(170), 1,
      anon_sym_PERCENT,
    ACTIONS(197), 1,
      anon_sym_RBRACK,
    STATE(81), 1,
      sym__raw_character,
    ACTIONS(166), 2,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
    ACTIONS(168), 2,
      anon_sym_DASH,
      anon_sym_LPAREN,
    STATE(46), 3,
      sym__class,
      sym_range,
      aux_sym_set_repeat1,
  [1164] = 6,
    ACTIONS(170), 1,
      anon_sym_PERCENT,
    ACTIONS(199), 1,
      anon_sym_RBRACK,
    STATE(81), 1,
      sym__raw_character,
    ACTIONS(166), 2,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
    ACTIONS(168), 2,
      anon_sym_DASH,
      anon_sym_LPAREN,
    STATE(46), 3,
      sym__class,
      sym_range,
      aux_sym_set_repeat1,
  [1187] = 6,
    ACTIONS(170), 1,
      anon_sym_PERCENT,
    ACTIONS(201), 1,
      anon_sym_RBRACK,
    STATE(81), 1,
      sym__raw_character,
    ACTIONS(166), 2,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
    ACTIONS(168), 2,
      anon_sym_DASH,
      anon_sym_LPAREN,
    STATE(46), 3,
      sym__class,
      sym_range,
      aux_sym_set_repeat1,
  [1210] = 6,
    ACTIONS(170), 1,
      anon_sym_PERCENT,
    ACTIONS(203), 1,
      anon_sym_RBRACK,
    STATE(81), 1,
      sym__raw_character,
    ACTIONS(166), 2,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
    ACTIONS(168), 2,
      anon_sym_DASH,
      anon_sym_LPAREN,
    STATE(46), 3,
      sym__class,
      sym_range,
      aux_sym_set_repeat1,
  [1233] = 6,
    ACTIONS(170), 1,
      anon_sym_PERCENT,
    ACTIONS(205), 1,
      anon_sym_RBRACK,
    STATE(81), 1,
      sym__raw_character,
    ACTIONS(166), 2,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
    ACTIONS(168), 2,
      anon_sym_DASH,
      anon_sym_LPAREN,
    STATE(46), 3,
      sym__class,
      sym_range,
      aux_sym_set_repeat1,
  [1256] = 5,
    ACTIONS(170), 1,
      anon_sym_PERCENT,
    STATE(81), 1,
      sym__raw_character,
    ACTIONS(166), 2,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
    ACTIONS(168), 2,
      anon_sym_DASH,
      anon_sym_LPAREN,
    STATE(51), 3,
      sym__class,
      sym_range,
      aux_sym_set_repeat1,
  [1276] = 5,
    ACTIONS(170), 1,
      anon_sym_PERCENT,
    STATE(81), 1,
      sym__raw_character,
    ACTIONS(166), 2,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
    ACTIONS(168), 2,
      anon_sym_DASH,
      anon_sym_LPAREN,
    STATE(50), 3,
      sym__class,
      sym_range,
      aux_sym_set_repeat1,
  [1296] = 5,
    ACTIONS(170), 1,
      anon_sym_PERCENT,
    STATE(81), 1,
      sym__raw_character,
    ACTIONS(166), 2,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
    ACTIONS(168), 2,
      anon_sym_DASH,
      anon_sym_LPAREN,
    STATE(54), 3,
      sym__class,
      sym_range,
      aux_sym_set_repeat1,
  [1316] = 5,
    ACTIONS(170), 1,
      anon_sym_PERCENT,
    STATE(81), 1,
      sym__raw_character,
    ACTIONS(166), 2,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
    ACTIONS(168), 2,
      anon_sym_DASH,
      anon_sym_LPAREN,
    STATE(48), 3,
      sym__class,
      sym_range,
      aux_sym_set_repeat1,
  [1336] = 2,
    ACTIONS(134), 3,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
    ACTIONS(132), 5,
      ts_builtin_sym_end,
      anon_sym_DOLLAR,
      anon_sym_PERCENTf,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
  [1349] = 2,
    ACTIONS(209), 3,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
    ACTIONS(207), 5,
      ts_builtin_sym_end,
      anon_sym_DOLLAR,
      anon_sym_PERCENTf,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
  [1362] = 2,
    ACTIONS(213), 3,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
    ACTIONS(211), 5,
      ts_builtin_sym_end,
      anon_sym_DOLLAR,
      anon_sym_PERCENTf,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
  [1375] = 2,
    ACTIONS(217), 3,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
    ACTIONS(215), 5,
      ts_builtin_sym_end,
      anon_sym_DOLLAR,
      anon_sym_PERCENTf,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
  [1388] = 2,
    ACTIONS(221), 3,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
    ACTIONS(219), 5,
      ts_builtin_sym_end,
      anon_sym_DOLLAR,
      anon_sym_PERCENTf,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
  [1401] = 2,
    ACTIONS(225), 3,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
    ACTIONS(223), 5,
      ts_builtin_sym_end,
      anon_sym_DOLLAR,
      anon_sym_PERCENTf,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
  [1414] = 2,
    ACTIONS(112), 3,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
    ACTIONS(110), 5,
      ts_builtin_sym_end,
      anon_sym_DOLLAR,
      anon_sym_PERCENTf,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
  [1427] = 2,
    ACTIONS(229), 3,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
    ACTIONS(227), 5,
      ts_builtin_sym_end,
      anon_sym_DOLLAR,
      anon_sym_PERCENTf,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
  [1440] = 3,
    ACTIONS(231), 1,
      ts_builtin_sym_end,
    ACTIONS(209), 3,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
    ACTIONS(207), 4,
      anon_sym_DOLLAR,
      anon_sym_PERCENTf,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
  [1455] = 2,
    ACTIONS(130), 3,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
    ACTIONS(128), 5,
      ts_builtin_sym_end,
      anon_sym_DOLLAR,
      anon_sym_PERCENTf,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
  [1468] = 2,
    ACTIONS(130), 3,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
    ACTIONS(128), 4,
      anon_sym_PERCENTf,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [1480] = 2,
    ACTIONS(217), 3,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
    ACTIONS(215), 4,
      anon_sym_PERCENTf,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [1492] = 2,
    ACTIONS(221), 3,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
    ACTIONS(219), 4,
      anon_sym_PERCENTf,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [1504] = 2,
    ACTIONS(225), 3,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
    ACTIONS(223), 4,
      anon_sym_PERCENTf,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [1516] = 2,
    ACTIONS(134), 3,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
    ACTIONS(132), 4,
      anon_sym_PERCENTf,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [1528] = 2,
    ACTIONS(112), 3,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
    ACTIONS(110), 4,
      anon_sym_PERCENTf,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [1540] = 2,
    ACTIONS(229), 3,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
      anon_sym_PERCENT,
    ACTIONS(227), 4,
      anon_sym_PERCENTf,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [1552] = 2,
    ACTIONS(156), 2,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
    ACTIONS(154), 4,
      anon_sym_DASH,
      anon_sym_PERCENT,
      anon_sym_LPAREN,
      anon_sym_RBRACK,
  [1563] = 2,
    ACTIONS(233), 2,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
    ACTIONS(235), 4,
      anon_sym_DASH,
      anon_sym_PERCENT,
      anon_sym_LPAREN,
      anon_sym_RBRACK,
  [1574] = 2,
    ACTIONS(160), 2,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
    ACTIONS(158), 4,
      anon_sym_DASH,
      anon_sym_PERCENT,
      anon_sym_LPAREN,
      anon_sym_RBRACK,
  [1585] = 2,
    ACTIONS(152), 2,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
    ACTIONS(150), 4,
      anon_sym_DASH,
      anon_sym_PERCENT,
      anon_sym_LPAREN,
      anon_sym_RBRACK,
  [1596] = 2,
    ACTIONS(237), 2,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
    ACTIONS(239), 4,
      anon_sym_DASH,
      anon_sym_PERCENT,
      anon_sym_LPAREN,
      anon_sym_RBRACK,
  [1607] = 3,
    ACTIONS(241), 1,
      anon_sym_DASH,
    ACTIONS(237), 2,
      aux_sym__raw_character_token1,
      anon_sym_DOT,
    ACTIONS(239), 3,
      anon_sym_PERCENT,
      anon_sym_LPAREN,
      anon_sym_RBRACK,
  [1620] = 2,
    ACTIONS(244), 1,
      anon_sym_LBRACK,
    STATE(39), 2,
      sym_set,
      sym_negated_set,
  [1628] = 2,
    ACTIONS(246), 1,
      anon_sym_LBRACK,
    STATE(35), 2,
      sym_set,
      sym_negated_set,
  [1636] = 1,
    ACTIONS(248), 1,
      aux_sym_balanced_match_token1,
  [1640] = 1,
    ACTIONS(250), 1,
      aux_sym_balanced_match_token1,
  [1644] = 1,
    ACTIONS(21), 1,
      ts_builtin_sym_end,
  [1648] = 1,
    ACTIONS(252), 1,
      ts_builtin_sym_end,
  [1652] = 1,
    ACTIONS(254), 1,
      aux_sym_balanced_match_token1,
  [1656] = 1,
    ACTIONS(256), 1,
      aux_sym_balanced_match_token1,
  [1660] = 1,
    ACTIONS(258), 1,
      aux_sym_balanced_match_token1,
  [1664] = 1,
    ACTIONS(19), 1,
      ts_builtin_sym_end,
  [1668] = 1,
    ACTIONS(260), 1,
      aux_sym_balanced_match_token1,
  [1672] = 1,
    ACTIONS(262), 1,
      ts_builtin_sym_end,
  [1676] = 1,
    ACTIONS(264), 1,
      aux_sym_range_token1,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 41,
  [SMALL_STATE(4)] = 82,
  [SMALL_STATE(5)] = 123,
  [SMALL_STATE(6)] = 161,
  [SMALL_STATE(7)] = 196,
  [SMALL_STATE(8)] = 231,
  [SMALL_STATE(9)] = 266,
  [SMALL_STATE(10)] = 301,
  [SMALL_STATE(11)] = 336,
  [SMALL_STATE(12)] = 357,
  [SMALL_STATE(13)] = 378,
  [SMALL_STATE(14)] = 399,
  [SMALL_STATE(15)] = 423,
  [SMALL_STATE(16)] = 447,
  [SMALL_STATE(17)] = 471,
  [SMALL_STATE(18)] = 495,
  [SMALL_STATE(19)] = 515,
  [SMALL_STATE(20)] = 539,
  [SMALL_STATE(21)] = 559,
  [SMALL_STATE(22)] = 583,
  [SMALL_STATE(23)] = 600,
  [SMALL_STATE(24)] = 617,
  [SMALL_STATE(25)] = 640,
  [SMALL_STATE(26)] = 663,
  [SMALL_STATE(27)] = 686,
  [SMALL_STATE(28)] = 709,
  [SMALL_STATE(29)] = 732,
  [SMALL_STATE(30)] = 755,
  [SMALL_STATE(31)] = 774,
  [SMALL_STATE(32)] = 791,
  [SMALL_STATE(33)] = 810,
  [SMALL_STATE(34)] = 827,
  [SMALL_STATE(35)] = 844,
  [SMALL_STATE(36)] = 861,
  [SMALL_STATE(37)] = 877,
  [SMALL_STATE(38)] = 893,
  [SMALL_STATE(39)] = 909,
  [SMALL_STATE(40)] = 925,
  [SMALL_STATE(41)] = 941,
  [SMALL_STATE(42)] = 957,
  [SMALL_STATE(43)] = 980,
  [SMALL_STATE(44)] = 1003,
  [SMALL_STATE(45)] = 1026,
  [SMALL_STATE(46)] = 1049,
  [SMALL_STATE(47)] = 1072,
  [SMALL_STATE(48)] = 1095,
  [SMALL_STATE(49)] = 1118,
  [SMALL_STATE(50)] = 1141,
  [SMALL_STATE(51)] = 1164,
  [SMALL_STATE(52)] = 1187,
  [SMALL_STATE(53)] = 1210,
  [SMALL_STATE(54)] = 1233,
  [SMALL_STATE(55)] = 1256,
  [SMALL_STATE(56)] = 1276,
  [SMALL_STATE(57)] = 1296,
  [SMALL_STATE(58)] = 1316,
  [SMALL_STATE(59)] = 1336,
  [SMALL_STATE(60)] = 1349,
  [SMALL_STATE(61)] = 1362,
  [SMALL_STATE(62)] = 1375,
  [SMALL_STATE(63)] = 1388,
  [SMALL_STATE(64)] = 1401,
  [SMALL_STATE(65)] = 1414,
  [SMALL_STATE(66)] = 1427,
  [SMALL_STATE(67)] = 1440,
  [SMALL_STATE(68)] = 1455,
  [SMALL_STATE(69)] = 1468,
  [SMALL_STATE(70)] = 1480,
  [SMALL_STATE(71)] = 1492,
  [SMALL_STATE(72)] = 1504,
  [SMALL_STATE(73)] = 1516,
  [SMALL_STATE(74)] = 1528,
  [SMALL_STATE(75)] = 1540,
  [SMALL_STATE(76)] = 1552,
  [SMALL_STATE(77)] = 1563,
  [SMALL_STATE(78)] = 1574,
  [SMALL_STATE(79)] = 1585,
  [SMALL_STATE(80)] = 1596,
  [SMALL_STATE(81)] = 1607,
  [SMALL_STATE(82)] = 1620,
  [SMALL_STATE(83)] = 1628,
  [SMALL_STATE(84)] = 1636,
  [SMALL_STATE(85)] = 1640,
  [SMALL_STATE(86)] = 1644,
  [SMALL_STATE(87)] = 1648,
  [SMALL_STATE(88)] = 1652,
  [SMALL_STATE(89)] = 1656,
  [SMALL_STATE(90)] = 1660,
  [SMALL_STATE(91)] = 1664,
  [SMALL_STATE(92)] = 1668,
  [SMALL_STATE(93)] = 1672,
  [SMALL_STATE(94)] = 1676,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pattern, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pattern, 1),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pattern, 2),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_pattern_repeat1, 2),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_pattern_repeat1, 2), SHIFT_REPEAT(60),
  [28] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_pattern_repeat1, 2), SHIFT_REPEAT(33),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_pattern_repeat1, 2), SHIFT_REPEAT(83),
  [34] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_pattern_repeat1, 2), SHIFT_REPEAT(12),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_pattern_repeat1, 2), SHIFT_REPEAT(45),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_pattern_repeat1, 2), SHIFT_REPEAT(9),
  [43] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_capture_repeat1, 2), SHIFT_REPEAT(36),
  [46] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_capture_repeat1, 2), SHIFT_REPEAT(82),
  [49] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_capture_repeat1, 2), SHIFT_REPEAT(13),
  [52] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_capture_repeat1, 2), SHIFT_REPEAT(49),
  [55] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_capture_repeat1, 2), SHIFT_REPEAT(7),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_capture_repeat1, 2),
  [60] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [64] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_class, 1),
  [92] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_class, 1),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_set, 3),
  [100] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_set, 3),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_negated_set, 4),
  [106] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_negated_set, 4),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_capture, 3),
  [112] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_capture, 3),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_character, 1),
  [118] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_character, 1),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_capture, 2),
  [124] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_capture, 2),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_set, 4),
  [130] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_set, 4),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_negated_set, 5),
  [134] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_negated_set, 5),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__class, 2),
  [152] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__class, 2),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__raw_character, 1),
  [156] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__raw_character, 1),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_balanced_match, 3, .production_id = 2),
  [160] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_balanced_match, 3, .production_id = 2),
  [162] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_frontier_pattern, 2),
  [164] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_frontier_pattern, 2),
  [166] = {.entry = {.count = 1, .reusable = false}}, SHIFT(76),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [180] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_set_repeat1, 2), SHIFT_REPEAT(76),
  [183] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_set_repeat1, 2), SHIFT_REPEAT(80),
  [186] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_set_repeat1, 2), SHIFT_REPEAT(11),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_set_repeat1, 2),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [207] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_pattern_repeat1, 1, .production_id = 1),
  [209] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_pattern_repeat1, 1, .production_id = 1),
  [211] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_anchor_begin, 1),
  [213] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_anchor_begin, 1),
  [215] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_character, 2),
  [217] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_character, 2),
  [219] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_shortest_zero_or_more, 1),
  [221] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_shortest_zero_or_more, 1),
  [223] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_class, 2),
  [225] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_class, 2),
  [227] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_capture, 4),
  [229] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_capture, 4),
  [231] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_anchor_end, 1),
  [233] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_range, 3, .dynamic_precedence = 1, .production_id = 3),
  [235] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_range, 3, .dynamic_precedence = 1, .production_id = 3),
  [237] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_set_repeat1, 1, .production_id = 1),
  [239] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_set_repeat1, 1, .production_id = 1),
  [241] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_set_repeat1, 1, .production_id = 1), SHIFT(94),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [252] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pattern, 3),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [262] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_luap(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
